import type { Locale } from "@/lib/i18n";

const fr = {
  metadata: {
    title: "AlmaGo | Études en Allemagne",
    description: "Préparez votre projet d’études en Allemagne avec AlmaGo, étape par étape.",
    keywords: ["études en Allemagne", "dossier étudiant", "programmes Allemagne", "candidatures Allemagne", "AlmaGo"],
  },
  common: {
    language: "Langue",
    homeAria: "AlmaGo accueil",
    skip: "Aller au contenu",
  },
  home: {
    nav: {
      journey: "Le parcours",
      space: "Mon espace",
      why: "Pourquoi AlmaGo",
      questions: "Questions",
      login: "Se connecter",
      signup: "Créer mon dossier",
      openMenu: "Ouvrir le menu",
      closeMenu: "Fermer le menu",
      mainNavigation: "Navigation principale",
      mobileNavigation: "Navigation mobile",
    },
    hero: {
      eyebrow: "Étudier en Allemagne, étape par étape.",
      title1: "Votre projet d’études",
      title2: "en Allemagne,",
      title3: "plus clair.",
      lead: "AlmaGo vous aide à préparer votre dossier, comparer des programmes et savoir quoi faire ensuite.",
      primary: "Créer mon dossier",
      secondary: "Voir les étapes",
      proof: ["6 étapes simples", "Documents au même endroit", "Sources officielles à vérifier"],
      exampleAria: "Exemple de dossier AlmaGo",
      exampleTitle: "Votre dossier avance",
      sample: "Exemple",
      rows: [
        ["Mon projet", "Objectif indiqué", "Indiqué"],
        ["Mes documents", "À préparer maintenant", ""],
        ["Mes candidatures", "À suivre", ""],
      ],
    },
    quick: {
      aria: "Accès rapides",
      navAria: "Accès rapide",
      items: [
        ["Trouver un programme", "Programmes et critères"],
        ["Voir les étapes", "Ce qu’il faut faire"],
        ["Préparer mes documents", "Documents à ajouter"],
        ["Préparer mon départ", "Langue, financement, assurance"],
        ["Voir les questions", "Réponses utiles"],
      ],
    },
    photo: {
      eyebrow: "Votre projet d’études d’abord",
      title1: "Préparez la suite",
      title2: "au bon moment.",
      text: "Commencez par le programme et les documents. Préparez ensuite le reste, au bon moment.",
      regionAria: "Étapes du parcours étudiant, faites défiler horizontalement",
      cards: ["Je compare les programmes", "Je prépare mes documents", "Je prépare mes candidatures"],
      alts: [
        "Des étudiantes se déplacent sur un campus avec un ordinateur et des documents.",
        "Des étudiants travaillent ensemble dans une bibliothèque universitaire.",
        "Deux étudiants discutent devant l’entrée d’un établissement universitaire.",
      ],
    },
    journey: {
      eyebrow: "Votre parcours, simplement",
      title1: "Six étapes",
      title2: "pour avancer.",
      intro: "Vous n’avez pas besoin de tout savoir maintenant. Faites une étape à la fois.",
      aria: "Les six étapes de votre projet d’études",
      steps: [
        ["Définir mon projet", "Choisissez le diplôme, le domaine, la langue et la rentrée qui vous intéressent.", "Mon point de départ"],
        ["Préparer mes documents", "Ajoutez vos diplômes et les documents que vous avez déjà.", "Mes études"],
        ["Comparer les programmes", "Regardez les critères, les dates et la source officielle.", "Mes options"],
        ["Préparer mes candidatures", "Pour chaque programme, voyez les documents et la prochaine action.", "Mes dossiers"],
        ["Préparer le départ", "Voyez ce dont vous aurez besoin selon votre projet.", "Langue, budget, assurance"],
        ["Suivre mes étapes", "Voyez ce qui est fait et ce qu’il reste à faire.", "La suite"],
      ],
      foot: "AlmaGo vous aide à préparer. Les universités et les autorités prennent les décisions.",
      cta: "Commencer mon dossier",
    },
    tools: {
      eyebrow: "Pour avancer",
      title: "Choisissez par où commencer.",
      intro: "Trois façons simples d’avancer dans votre projet.",
      items: [
        ["Voir par où commencer", "Indiquez votre diplôme, votre domaine, votre langue et votre rentrée.", "Commencer mon dossier"],
        ["Comparer les programmes", "Regardez les critères, les dates et la source officielle.", "Voir les programmes"],
        ["Vérifier une information", "Voyez qui donne l’information et où la confirmer.", "Voir les sources"],
      ],
    },
    faq: {
      eyebrow: "Questions utiles",
      title1: "Avant de faire",
      title2: "le premier pas.",
      intro: "Les réponses aux questions les plus fréquentes.",
      cta: "Voir les étapes",
      items: [
        ["Puis-je commencer sans admission ?", "Oui. Commencez par votre projet et les documents que vous avez. Cherchez ensuite une admission adaptée avant les démarches qui en dépendent."],
        ["Que vais-je retrouver dans mon espace ?", "Votre projet, vos documents, vos programmes, vos candidatures et vos prochaines étapes."],
        ["AlmaGo dépose-t-il mes candidatures ?", "Non. AlmaGo vous aide à préparer et suivre vos candidatures. Vous les envoyez par le canal demandé par l’université, par exemple directement ou via uni-assist."],
        ["Les informations sont-elles officielles ?", "AlmaGo indique la source et la date de contrôle quand elles sont disponibles. Vérifiez toujours la source officielle avant une démarche."],
        ["AlmaGo garantit-il une admission ou un visa ?", "Non. AlmaGo organise votre préparation. Les universités, ambassades et autorités prennent les décisions."],
      ],
    },
    closing: {
      eyebrow: "Commencez simplement",
      title1: "Commencez",
      title2: "par votre projet.",
      text: "Créez votre dossier. Vous ajouterez vos documents et vos prochaines étapes ensuite.",
      proofAria: "Ce que votre dossier rassemble",
      proof: ["Projet", "Documents", "Prochaines étapes"],
      cta: "Créer mon dossier",
      login: "J’ai déjà un compte",
    },
    footer: {
      tagline: "Votre dossier d’études, étape par étape.",
      independent: "Plateforme indépendante",
      columns: [
        ["Parcours", [["Les six étapes", "#parcours"], ["Outils utiles", "#outils"], ["Questions fréquentes", "#faq"]]],
        ["Préparer", [["Mon espace", "/login"], ["Comparer les programmes", "#programmes"], ["Créer mon dossier", "/signup"]]],
        ["Repères", [["Se connecter", "/login"], ["uni-assist · source externe", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo organise votre préparation. Les admissions, visas et autres décisions officielles appartiennent aux organismes compétents.",
      photoCredit1: "Photographies d’illustration :",
      photoCredit2: "Les personnes représentées ne sont pas présentées comme utilisatrices d’AlmaGo.",
    },
  },
  auth: {
    studentSpace: "Espace étudiant",
    loginStory: {
      eyebrow: "Votre espace AlmaGo",
      title: "Retrouvez votre prochaine étape.",
      description: "Votre dossier reste au même endroit.",
      badge: "Votre dossier reste organisé",
      points: [
        ["Votre prochaine action", "Voyez rapidement ce qu’il faut faire."],
        ["Vos documents", "Retrouvez ce qui est ajouté ou à vérifier."],
        ["Vos candidatures", "Suivez chaque programme au même endroit."],
      ],
    },
    signupStory: {
      eyebrow: "Votre parcours commence ici",
      title: "Créez votre espace.",
      description: "Vous indiquerez ensuite votre projet et vos documents.",
      badge: "Étudier en Allemagne, étape par étape",
      points: [
        ["Créer votre compte", "Vos informations de connexion."],
        ["Définir votre projet", "Diplôme, domaine, langue et rentrée."],
        ["Préparer votre dossier", "Documents, programmes et candidatures."],
      ],
    },
    boundaryTitle: "AlmaGo vous aide à préparer.",
    boundaryText: "Les universités et les autorités prennent les décisions officielles.",
    titles: {
      login: "Se connecter",
      signup: "Créer mon compte",
      forgot: "Réinitialiser mon mot de passe",
    },
    subtitles: {
      login: "Retrouvez votre dossier et votre prochaine étape.",
      signup: "Créez votre espace pour préparer votre dossier Allemagne.",
      forgot: "Indiquez votre email pour recevoir un lien.",
    },
    labels: {
      firstName: "Prénom",
      lastName: "Nom",
      email: "Email",
      password: "Mot de passe",
      show: "Afficher",
      hide: "Masquer",
      studentAccount: "Compte étudiant",
      minPassword: "8 caractères minimum",
      emailConfirmation: "Confirmation par email",
      alreadyAccount: "Déjà un compte ?",
      forgotPassword: "Mot de passe oublié ?",
      backLogin: "Retour à la connexion",
      createAccount: "Créer un compte",
      login: "Se connecter",
      signup: "Créer mon compte",
      sendLink: "Envoyer le lien",
      loading: "Patientez...",
    },
    placeholders: {
      firstName: "Votre prénom",
      lastName: "Votre nom",
      email: "vous@exemple.com",
    },
    messages: {
      resetSent: "Si cette adresse existe, un lien de réinitialisation a été envoyé.",
      checkEmail: "Vérifiez votre adresse email pour continuer.",
      invalidLogin: "Email ou mot de passe incorrect.",
      generic: "Impossible de continuer pour le moment. Réessayez.",
      signupError: "Impossible de créer le compte pour le moment. Vérifiez vos informations et réessayez.",
      resetError: "Impossible d’envoyer le lien pour le moment. Réessayez.",
    },
    mobile: {
      signupLink: "Créer un compte",
      loginLink: "Connexion",
    },
  },
  shell: {
    studentNameFallback: "étudiant",
    skip: "Aller au contenu",
    studentFile: "Dossier étudiant",
    studyProject: "Projet d’études en Allemagne",
    navigation: "Navigation",
    studentNavigation: "Navigation étudiant",
    studentMobileNavigation: "Navigation étudiant mobile",
    groups: ["Dossier", "Parcours", "Ressources"],
    items: [
      ["Mon dossier", "Vue d’ensemble"],
      ["Mon projet", "Point de départ"],
      ["Mon parcours", "Mes étapes en Allemagne"],
      ["Mon profil", "Mes informations"],
      ["Mes documents", "Pièces et statuts"],
      ["Mes programmes", "Programmes à comparer"],
      ["Cours de langue", "Cours à comparer"],
      ["Financement & assurance", "Options vérifiées"],
      ["Mes démarches", "Étapes du dossier"],
      ["Mes candidatures", "Suivi et échéances"],
    ],
    footer: "AlmaGo vous aide à préparer. Les organismes officiels prennent les décisions.",
    logout: "Déconnexion",
    hello: "Bonjour",
    mobileIntro: "Choisissez ce que vous voulez consulter.",
    personalFile: "Dossier personnel",
    desktopIntro: "Retrouvez ici votre prochaine étape.",
    openMenu: "Ouvrir le menu étudiant",
    closeMenu: "Fermer le menu étudiant",
    menu: "Menu",
    close: "Fermer",
  },
} as const;

const ar = {
  metadata: {
    title: "AlmaGo | الدراسة في ألمانيا",
    description: "يساعدك AlmaGo على تنظيم طريقك للدراسة في ألمانيا بخطوات واضحة.",
    keywords: ["الدراسة في ألمانيا", "ملف الطالب", "برامج الدراسة في ألمانيا", "التقديم للجامعات الألمانية", "AlmaGo"],
  },
  common: {
    language: "اللغة",
    homeAria: "الصفحة الرئيسية لـ AlmaGo",
    skip: "الانتقال إلى المحتوى",
  },
  home: {
    nav: {
      journey: "المسار",
      space: "ملفي",
      why: "لماذا AlmaGo؟",
      questions: "الأسئلة",
      login: "تسجيل الدخول",
      signup: "ابدأ ملفك",
      openMenu: "فتح القائمة",
      closeMenu: "إغلاق القائمة",
      mainNavigation: "القائمة الرئيسية",
      mobileNavigation: "قائمة الهاتف",
    },
    hero: {
      eyebrow: "كل ما تحتاجه لتنظيم ملفك الدراسي.",
      title1: "ابدأ دراستك",
      title2: "في ألمانيا",
      title3: "بخطوات واضحة.",
      lead: "ابحث عن البرنامج المناسب، جهّز مستنداتك، وتابع طلبات التقديم خطوة بخطوة مع AlmaGo.",
      primary: "ابدأ ملفك",
      secondary: "عرض الخطوات",
      proof: ["6 مراحل بسيطة", "كل مستنداتك في مكان واحد", "مصادر رسمية عند الحاجة"],
      exampleAria: "مثال على ملف AlmaGo",
      exampleTitle: "ملفك يتقدّم معك",
      sample: "مثال",
      rows: [
        ["هدفك الدراسي", "تم تحديده", "جاهز"],
        ["مستنداتك", "راجع المطلوب", ""],
        ["طلباتك", "تابع التقديم", ""],
      ],
    },
    quick: {
      aria: "وصول سريع",
      navAria: "روابط سريعة",
      items: [
        ["ابحث عن برنامج", "البرامج والشروط"],
        ["اعرف خطواتك", "ماذا تفعل الآن؟"],
        ["جهّز مستنداتك", "ما المطلوب في ملفك؟"],
        ["الاستعداد للسفر", "اللغة والتمويل والتأمين"],
        ["الأسئلة الشائعة", "إجابات مفيدة"],
      ],
    },
    photo: {
      eyebrow: "رتّب خطواتك من البداية",
      title1: "جهّز ما تحتاجه",
      title2: "خطوة بخطوة.",
      text: "ابدأ بالبرنامج المناسب، ثم جهّز مستنداتك وطلباتك عندما يحين وقتها.",
      regionAria: "مراحل مشروع الطالب، مرّر أفقياً",
      cards: ["قارن البرامج", "جهّز مستنداتك", "حضّر طلبات التقديم"],
      alts: [
        "طالبات في الحرم الجامعي يحملن حاسوباً ومستندات.",
        "طلاب يعملون معاً في مكتبة جامعية.",
        "طالبان يتحدثان أمام مبنى جامعي.",
      ],
    },
    journey: {
      eyebrow: "طريق واضح من البداية",
      title1: "ست مراحل",
      title2: "تساعدك على التقدّم.",
      intro: "لا تحتاج إلى معرفة كل شيء من البداية. اتبع المراحل واحدة بعد الأخرى.",
      aria: "الخطوات الست لمشروع الدراسة",
      steps: [
        ["حدّد هدفك", "اختر الشهادة والمجال واللغة وموعد البداية المناسب لك.", "ابدأ من هنا"],
        ["جهّز مستنداتك", "أضف الشهادات والمستندات التي لديك.", "مستنداتك"],
        ["قارن البرامج", "راجع الشروط والمواعيد قبل أن تختار.", "برامجك"],
        ["حضّر طلباتك", "راجع المطلوب لكل برنامج ثم تابع التقديم.", "التقديم"],
        ["استعد للسفر", "راجع اللغة والميزانية والتأمين وما يخص حالتك.", "الاستعداد"],
        ["تابع تقدّمك", "اعرف ما أنجزته وما بقي عليك.", "خطوتك التالية"],
      ],
      foot: "AlmaGo يساعدك في التحضير؛ أما القرارات الرسمية فتتخذها الجامعات والجهات المختصة.",
      cta: "ابدأ ملفك",
    },
    tools: {
      eyebrow: "اختر ما يناسبك",
      title: "ابدأ من الخطوة التي تناسب وضعك.",
      intro: "يمكنك البدء من هدفك، أو من البرامج، أو من المعلومات التي تريد التحقق منها.",
      items: [
        ["عرّفنا بوضعك", "أدخل شهادتك ومجالك ومستواك اللغوي وموعد البداية.", "ابدأ ملفك"],
        ["قارن البرامج", "اطّلع على الشروط والمواعيد والمصدر الرسمي.", "عرض البرامج"],
        ["تحقق من المعلومات", "اعرف مصدر كل معلومة وأين يمكنك التأكد منها.", "عرض المصادر"],
      ],
    },
    faq: {
      eyebrow: "أسئلة مهمة",
      title1: "قبل أن تبدأ،",
      title2: "هذه أهم الإجابات.",
      intro: "إجابات قصيرة وواضحة عن الأسئلة التي قد تحتاجها في البداية.",
      cta: "عرض الخطوات",
      items: [
        ["هل يمكنني البدء من دون قبول جامعي؟", "نعم. يمكنك البدء بتحديد هدفك وتجهيز ما لديك من مستندات، ثم البحث عن قبول مناسب قبل الخطوات التي تتطلبه."],
        ["ماذا سأجد في ملفي؟", "ستجد مشروعك، مستنداتك، البرامج التي تقارنها، طلبات التقديم والخطوات التالية."],
        ["هل يرسل AlmaGo طلبات التقديم نيابةً عني؟", "لا. يساعدك AlmaGo على تجهيز طلباتك ومتابعتها. أنت ترسل الطلب بالطريقة التي تطلبها الجامعة، مباشرةً أو عبر uni-assist مثلاً."],
        ["هل المعلومات في AlmaGo رسمية؟", "يعرض AlmaGo المصدر وتاريخ التحقق عندما يكونان متاحين. راجع دائماً المصدر الرسمي قبل أي إجراء."],
        ["هل يضمن AlmaGo القبول أو التأشيرة؟", "لا. AlmaGo يساعدك على التحضير فقط. الجامعة والسفارة والسلطات المختصة هي التي تتخذ القرار."],
      ],
    },
    closing: {
      eyebrow: "جاهز للبدء؟",
      title1: "ابدأ ملفك",
      title2: "بخطوة بسيطة.",
      text: "أنشئ ملفك، أضف ما لديك من مستندات، ثم تابع الخطوات واحدة بعد الأخرى.",
      proofAria: "محتوى ملفك",
      proof: ["المشروع", "المستندات", "الخطوات التالية"],
      cta: "ابدأ ملفك",
      login: "لدي حساب بالفعل",
    },
    footer: {
      tagline: "كل ما تحتاجه لتنظيم ملف دراستك في مكان واحد.",
      independent: "منصة مستقلة",
      columns: [
        ["المسار", [["الخطوات الست", "#parcours"], ["أدوات مفيدة", "#outils"], ["الأسئلة الشائعة", "#faq"]]],
        ["التحضير", [["ملفي", "/login"], ["مقارنة البرامج", "#programmes"], ["ابدأ ملفك", "/signup"]]],
        ["روابط مفيدة", [["تسجيل الدخول", "/login"], ["uni-assist · مصدر خارجي", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo ينظم عملية التحضير. القبول والتأشيرة والقرارات الرسمية الأخرى تبقى من اختصاص الجهات المختصة.",
      photoCredit1: "الصور التوضيحية:",
      photoCredit2: "الأشخاص الظاهرون في الصور لا يتم تقديمهم على أنهم مستخدمون لـ AlmaGo.",
    },
  },
  auth: {
    studentSpace: "مساحتي",
    loginStory: {
      eyebrow: "ملفك على AlmaGo",
      title: "سجّل الدخول وتابع من حيث توقفت.",
      description: "ستجد مستنداتك وبرامجك وخطواتك في مكان واحد.",
      badge: "كل شيء في مكان واحد",
      points: [
        ["الخطوة التالية", "اعرف مباشرة ما الذي عليك فعله."],
        ["مستنداتك", "راجع ما أضفته وما يحتاج إلى تحديث."],
        ["طلباتك", "تابع برامجك وطلبات التقديم بسهولة."],
      ],
    },
    signupStory: {
      eyebrow: "ابدأ من هنا",
      title: "أنشئ حسابك وابدأ.",
      description: "بعد إنشاء الحساب، نساعدك على تحديد هدفك وتجهيز ملفك خطوة بخطوة.",
      badge: "طريق أوضح للدراسة في ألمانيا",
      points: [
        ["أنشئ حسابك", "ابدأ ببيانات الدخول الأساسية."],
        ["حدّد هدفك", "اختر الشهادة والمجال واللغة وموعد البداية."],
        ["جهّز ملفك", "أضف مستنداتك وقارن البرامج وتابع طلباتك."],
      ],
    },
    boundaryTitle: "AlmaGo يساعدك على تنظيم ملفك.",
    boundaryText: "الجامعات والسلطات المختصة هي التي تتخذ القرارات الرسمية.",
    titles: {
      login: "تسجيل الدخول",
      signup: "إنشاء حساب",
      forgot: "إعادة تعيين كلمة المرور",
    },
    subtitles: {
      login: "ارجع إلى ملفك وتابع من حيث توقفت.",
      signup: "أنشئ حسابك وابدأ تجهيز ملفك للدراسة في ألمانيا.",
      forgot: "أدخل بريدك الإلكتروني لنرسل لك رابطاً.",
    },
    labels: {
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      show: "إظهار",
      hide: "إخفاء",
      studentAccount: "حساب طالب",
      minPassword: "8 أحرف على الأقل",
      emailConfirmation: "تأكيد عبر البريد الإلكتروني",
      alreadyAccount: "لديك حساب بالفعل؟",
      forgotPassword: "نسيت كلمة المرور؟",
      backLogin: "العودة إلى تسجيل الدخول",
      createAccount: "إنشاء حساب",
      login: "تسجيل الدخول",
      signup: "إنشاء حساب",
      sendLink: "إرسال الرابط",
      loading: "يرجى الانتظار...",
    },
    placeholders: {
      firstName: "اسمك الأول",
      lastName: "اسم العائلة",
      email: "you@example.com",
    },
    messages: {
      resetSent: "إذا كان هذا البريد مسجلاً، فقد أرسلنا رابط إعادة التعيين.",
      checkEmail: "تحقق من بريدك الإلكتروني للمتابعة.",
      invalidLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      generic: "تعذر إكمال العملية الآن. حاول مرة أخرى.",
      signupError: "تعذر إنشاء الحساب الآن. تحقق من بياناتك وحاول مرة أخرى.",
      resetError: "تعذر إرسال الرابط الآن. حاول مرة أخرى.",
    },
    mobile: {
      signupLink: "إنشاء حساب",
      loginLink: "تسجيل الدخول",
    },
  },
  shell: {
    studentNameFallback: "طالب",
    skip: "الانتقال إلى المحتوى",
    studentFile: "ملف الطالب",
    studyProject: "مشروع الدراسة في ألمانيا",
    navigation: "التنقل",
    studentNavigation: "قائمة الطالب",
    studentMobileNavigation: "قائمة الطالب على الهاتف",
    groups: ["ملفي", "خطواتي", "الموارد"],
    items: [
      ["ملفي", "نظرة عامة"],
      ["مشروعي", "نقطة البداية"],
      ["مساري", "خطواتي في ألمانيا"],
      ["بياناتي", "معلوماتي"],
      ["مستنداتي", "الملفات والحالة"],
      ["برامجي", "برامج للمقارنة"],
      ["دورات اللغة", "دورات للمقارنة"],
      ["التمويل والتأمين", "خيارات تم التحقق منها"],
      ["خطواتي", "مراحل الملف"],
      ["طلبات التقديم", "المتابعة والمواعيد"],
    ],
    footer: "AlmaGo يساعدك على التحضير. الجهات الرسمية هي التي تتخذ القرارات.",
    logout: "تسجيل الخروج",
    hello: "مرحباً",
    mobileIntro: "اختر ما تريد الاطلاع عليه.",
    personalFile: "ملفي الشخصي",
    desktopIntro: "هنا تجد أهم ما يخص ملفك وخطوتك التالية.",
    openMenu: "فتح قائمة الطالب",
    closeMenu: "إغلاق قائمة الطالب",
    menu: "القائمة",
    close: "إغلاق",
  },
} as const;

const en = {
  metadata: {
    title: "AlmaGo | Study in Germany",
    description: "Plan your studies in Germany with AlmaGo, one clear step at a time.",
    keywords: ["study in Germany", "student application", "German university programmes", "Germany applications", "AlmaGo"],
  },
  common: {
    language: "Language",
    homeAria: "AlmaGo home",
    skip: "Skip to content",
  },
  home: {
    nav: {
      journey: "Your journey",
      space: "My space",
      why: "Why AlmaGo",
      questions: "Questions",
      login: "Sign in",
      signup: "Start my file",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      mainNavigation: "Main navigation",
      mobileNavigation: "Mobile navigation",
    },
    hero: {
      eyebrow: "Study in Germany, step by step.",
      title1: "Your study plans",
      title2: "for Germany,",
      title3: "made clearer.",
      lead: "AlmaGo helps you organise your documents, compare programmes and see what to do next.",
      primary: "Start my file",
      secondary: "See the steps",
      proof: ["6 clear steps", "Documents in one place", "Official sources to check"],
      exampleAria: "Example AlmaGo file",
      exampleTitle: "Your file is moving forward",
      sample: "Example",
      rows: [
        ["My plan", "Goal added", "Added"],
        ["My documents", "Next to prepare", ""],
        ["My applications", "To follow", ""],
      ],
    },
    quick: {
      aria: "Quick access",
      navAria: "Quick links",
      items: [
        ["Find a programme", "Programmes and requirements"],
        ["See the steps", "What to do next"],
        ["Prepare my documents", "Documents to add"],
        ["Plan my move", "Language, funding and insurance"],
        ["Read common questions", "Useful answers"],
      ],
    },
    photo: {
      eyebrow: "Start with your study plan",
      title1: "Prepare the next step",
      title2: "at the right time.",
      text: "Start with the programme and your documents. Prepare the rest when it becomes relevant.",
      regionAria: "Student journey steps, scroll horizontally",
      cards: ["I compare programmes", "I prepare my documents", "I prepare my applications"],
      alts: [
        "Students walking across a campus with a laptop and documents.",
        "Students working together in a university library.",
        "Two students talking outside a university building.",
      ],
    },
    journey: {
      eyebrow: "Your journey, made simple",
      title1: "Six steps",
      title2: "to move forward.",
      intro: "You do not need to know everything at once. Take it one step at a time.",
      aria: "Six steps in your study journey",
      steps: [
        ["Set my goal", "Choose the degree, subject, language and intake you are aiming for.", "Where I start"],
        ["Prepare my documents", "Add your qualifications and the documents you already have.", "My studies"],
        ["Compare programmes", "Check the requirements, deadlines and official source.", "My options"],
        ["Prepare my applications", "For each programme, see the documents and next action.", "My applications"],
        ["Plan the move", "See what you may need based on your plan.", "Language, budget, insurance"],
        ["Track my progress", "See what is done and what still needs attention.", "What comes next"],
      ],
      foot: "AlmaGo helps you prepare. Universities and public authorities make the official decisions.",
      cta: "Start my file",
    },
    tools: {
      eyebrow: "Get started",
      title: "Choose where to begin.",
      intro: "Three simple ways to move your plan forward.",
      items: [
        ["See where to start", "Add your qualification, subject, language level and intake.", "Start my file"],
        ["Compare programmes", "Check requirements, deadlines and the official source.", "See programmes"],
        ["Check information", "See who provides the information and where to confirm it.", "See sources"],
      ],
    },
    faq: {
      eyebrow: "Useful questions",
      title1: "Before you take",
      title2: "the first step.",
      intro: "Short answers to the questions students ask most.",
      cta: "See the steps",
      items: [
        ["Can I start without an admission offer?", "Yes. Start with your plan and the documents you already have. Then look for a suitable admission route before steps that depend on it."],
        ["What will I find in my space?", "Your study plan, documents, programmes, applications and next steps."],
        ["Does AlmaGo submit applications for me?", "No. AlmaGo helps you prepare and track them. You submit through the route required by the university, for example directly or through uni-assist."],
        ["Is the information official?", "AlmaGo shows the source and review date when available. Always check the official source before taking action."],
        ["Does AlmaGo guarantee admission or a visa?", "No. AlmaGo helps you prepare. Universities, embassies and public authorities make the decisions."],
      ],
    },
    closing: {
      eyebrow: "Start simply",
      title1: "Start with",
      title2: "your study plan.",
      text: "Create your file first. You can add documents and work through the next steps afterwards.",
      proofAria: "What your file brings together",
      proof: ["Study plan", "Documents", "Next steps"],
      cta: "Start my file",
      login: "I already have an account",
    },
    footer: {
      tagline: "Your study file, step by step.",
      independent: "Independent platform",
      columns: [
        ["Journey", [["The six steps", "#parcours"], ["Useful tools", "#outils"], ["Common questions", "#faq"]]],
        ["Prepare", [["My space", "/login"], ["Compare programmes", "#programmes"], ["Start my file", "/signup"]]],
        ["Useful links", [["Sign in", "/login"], ["uni-assist · external source", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo organises your preparation. Admission, visa and other official decisions remain with the responsible authorities.",
      photoCredit1: "Illustration photos:",
      photoCredit2: "People shown in these photos are not presented as AlmaGo users.",
    },
  },
  auth: {
    studentSpace: "Student space",
    loginStory: {
      eyebrow: "Your AlmaGo space",
      title: "Pick up from your next step.",
      description: "Your study file stays organised in one place.",
      badge: "Keep your file organised",
      points: [
        ["Your next action", "See what needs your attention now."],
        ["Your documents", "Find what you added and what still needs checking."],
        ["Your applications", "Track each programme in one place."],
      ],
    },
    signupStory: {
      eyebrow: "Your journey starts here",
      title: "Create your space.",
      description: "Next, you can add your study plan and documents.",
      badge: "Study in Germany, step by step",
      points: [
        ["Create your account", "Your sign-in details."],
        ["Set your study plan", "Degree, subject, language and intake."],
        ["Prepare your file", "Documents, programmes and applications."],
      ],
    },
    boundaryTitle: "AlmaGo helps you prepare.",
    boundaryText: "Universities and public authorities make the official decisions.",
    titles: {
      login: "Sign in",
      signup: "Create my account",
      forgot: "Reset my password",
    },
    subtitles: {
      login: "Open your file and see what to do next.",
      signup: "Create your space to start preparing your Germany study file.",
      forgot: "Enter your email and we will send you a reset link.",
    },
    labels: {
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      password: "Password",
      show: "Show",
      hide: "Hide",
      studentAccount: "Student account",
      minPassword: "At least 8 characters",
      emailConfirmation: "Email confirmation",
      alreadyAccount: "Already have an account?",
      forgotPassword: "Forgot your password?",
      backLogin: "Back to sign in",
      createAccount: "Create an account",
      login: "Sign in",
      signup: "Create my account",
      sendLink: "Send reset link",
      loading: "Please wait...",
    },
    placeholders: {
      firstName: "Your first name",
      lastName: "Your last name",
      email: "you@example.com",
    },
    messages: {
      resetSent: "If this email is registered, we have sent a reset link.",
      checkEmail: "Check your email to continue.",
      invalidLogin: "Email or password is incorrect.",
      generic: "We could not complete this right now. Please try again.",
      signupError: "We could not create the account. Check your details and try again.",
      resetError: "We could not send the reset link. Please try again.",
    },
    mobile: {
      signupLink: "Create account",
      loginLink: "Sign in",
    },
  },
  shell: {
    studentNameFallback: "student",
    skip: "Skip to content",
    studentFile: "Student file",
    studyProject: "Study plans for Germany",
    navigation: "Navigation",
    studentNavigation: "Student navigation",
    studentMobileNavigation: "Student mobile navigation",
    groups: ["My file", "My journey", "Resources"],
    items: [
      ["My overview", "At a glance"],
      ["My study plan", "Where I start"],
      ["My journey", "My steps in Germany"],
      ["My profile", "My information"],
      ["My documents", "Files and status"],
      ["My programmes", "Programmes to compare"],
      ["Language courses", "Courses to compare"],
      ["Funding & insurance", "Checked options"],
      ["My steps", "What to do next"],
      ["My applications", "Progress and deadlines"],
    ],
    footer: "AlmaGo helps you prepare. Official bodies make the decisions.",
    logout: "Sign out",
    hello: "Hello",
    mobileIntro: "Choose what you want to open.",
    personalFile: "Personal file",
    desktopIntro: "See your next step here.",
    openMenu: "Open student menu",
    closeMenu: "Close student menu",
    menu: "Menu",
    close: "Close",
  },
} as const;

const de = {
  metadata: {
    title: "AlmaGo | Studium in Deutschland",
    description: "Plane dein Studium in Deutschland mit AlmaGo – Schritt für Schritt.",
    keywords: ["Studium in Deutschland", "Bewerbung Studium", "Studiengänge Deutschland", "Uni Bewerbung Deutschland", "AlmaGo"],
  },
  common: {
    language: "Sprache",
    homeAria: "AlmaGo Startseite",
    skip: "Zum Inhalt springen",
  },
  home: {
    nav: {
      journey: "Mein Weg",
      space: "Mein Bereich",
      why: "Warum AlmaGo",
      questions: "Fragen",
      login: "Anmelden",
      signup: "Akte starten",
      openMenu: "Menü öffnen",
      closeMenu: "Menü schließen",
      mainNavigation: "Hauptnavigation",
      mobileNavigation: "Mobile Navigation",
    },
    hero: {
      eyebrow: "Studieren in Deutschland – Schritt für Schritt.",
      title1: "Dein Studienplan",
      title2: "für Deutschland,",
      title3: "klarer gemacht.",
      lead: "AlmaGo hilft dir, Unterlagen vorzubereiten, Studiengänge zu vergleichen und den nächsten Schritt zu sehen.",
      primary: "Akte starten",
      secondary: "Schritte ansehen",
      proof: ["6 klare Schritte", "Unterlagen an einem Ort", "Offizielle Quellen zum Prüfen"],
      exampleAria: "Beispiel für eine AlmaGo-Akte",
      exampleTitle: "Deine Akte kommt voran",
      sample: "Beispiel",
      rows: [
        ["Mein Plan", "Ziel angegeben", "Erfasst"],
        ["Meine Unterlagen", "Als Nächstes vorbereiten", ""],
        ["Meine Bewerbungen", "Im Blick behalten", ""],
      ],
    },
    quick: {
      aria: "Schnellzugriff",
      navAria: "Schnellzugriff",
      items: [
        ["Studiengang finden", "Studiengänge und Voraussetzungen"],
        ["Schritte ansehen", "Was als Nächstes ansteht"],
        ["Unterlagen vorbereiten", "Unterlagen zum Hochladen"],
        ["Umzug vorbereiten", "Sprache, Finanzierung, Versicherung"],
        ["Häufige Fragen", "Kurze Antworten"],
      ],
    },
    photo: {
      eyebrow: "Dein Studienplan zuerst",
      title1: "Bereite den nächsten Schritt",
      title2: "zur richtigen Zeit vor.",
      text: "Starte mit dem Studiengang und deinen Unterlagen. Den Rest bereitest du vor, wenn er relevant wird.",
      regionAria: "Schritte im Studienweg, horizontal scrollen",
      cards: ["Ich vergleiche Studiengänge", "Ich bereite Unterlagen vor", "Ich bereite Bewerbungen vor"],
      alts: [
        "Studierende gehen mit Laptop und Unterlagen über einen Campus.",
        "Studierende arbeiten gemeinsam in einer Hochschulbibliothek.",
        "Zwei Studierende sprechen vor einem Hochschulgebäude.",
      ],
    },
    journey: {
      eyebrow: "Dein Weg, einfach erklärt",
      title1: "Sechs Schritte",
      title2: "bis zum nächsten Ziel.",
      intro: "Du musst nicht alles sofort wissen. Geh Schritt für Schritt vor.",
      aria: "Sechs Schritte deines Studienwegs",
      steps: [
        ["Mein Ziel festlegen", "Wähle Abschluss, Fach, Sprache und gewünschten Studienstart.", "Mein Startpunkt"],
        ["Unterlagen vorbereiten", "Füge deine Abschlüsse und vorhandenen Unterlagen hinzu.", "Meine Ausbildung"],
        ["Studiengänge vergleichen", "Prüfe Voraussetzungen, Fristen und die offizielle Quelle.", "Meine Optionen"],
        ["Bewerbungen vorbereiten", "Sieh für jeden Studiengang Unterlagen und nächste Aktion.", "Meine Bewerbungen"],
        ["Umzug vorbereiten", "Sieh, was du je nach deinem Plan brauchst.", "Sprache, Budget, Versicherung"],
        ["Fortschritt verfolgen", "Sieh, was erledigt ist und was noch fehlt.", "Wie es weitergeht"],
      ],
      foot: "AlmaGo hilft dir bei der Vorbereitung. Hochschulen und Behörden treffen die offiziellen Entscheidungen.",
      cta: "Akte starten",
    },
    tools: {
      eyebrow: "So kannst du starten",
      title: "Wähle deinen Einstieg.",
      intro: "Drei einfache Wege, mit deinem Plan weiterzukommen.",
      items: [
        ["Startpunkt finden", "Trage Abschluss, Fach, Sprache und Studienstart ein.", "Akte starten"],
        ["Studiengänge vergleichen", "Prüfe Voraussetzungen, Fristen und die offizielle Quelle.", "Studiengänge ansehen"],
        ["Information prüfen", "Sieh, von wem die Information kommt und wo du sie bestätigen kannst.", "Quellen ansehen"],
      ],
    },
    faq: {
      eyebrow: "Wichtige Fragen",
      title1: "Bevor du",
      title2: "den ersten Schritt machst.",
      intro: "Kurze Antworten auf häufige Fragen.",
      cta: "Schritte ansehen",
      items: [
        ["Kann ich ohne Zulassung anfangen?", "Ja. Starte mit deinem Studienplan und den Unterlagen, die du schon hast. Suche danach eine passende Zulassungsmöglichkeit, bevor du Schritte machst, die davon abhängen."],
        ["Was finde ich in meinem Bereich?", "Deinen Studienplan, Unterlagen, Studiengänge, Bewerbungen und nächsten Schritte."],
        ["Schickt AlmaGo meine Bewerbungen ab?", "Nein. AlmaGo hilft dir beim Vorbereiten und Nachverfolgen. Du reichst die Bewerbung über den von der Hochschule verlangten Weg ein, zum Beispiel direkt oder über uni-assist."],
        ["Sind die Informationen offiziell?", "AlmaGo zeigt Quelle und Prüfdatum, wenn sie verfügbar sind. Prüfe wichtige Angaben immer noch einmal bei der offiziellen Stelle."],
        ["Garantiert AlmaGo Zulassung oder Visum?", "Nein. AlmaGo hilft bei der Vorbereitung. Hochschulen, Botschaften und Behörden treffen die Entscheidungen."],
      ],
    },
    closing: {
      eyebrow: "Einfach anfangen",
      title1: "Starte mit",
      title2: "deinem Studienplan.",
      text: "Lege zuerst deine Akte an. Unterlagen und nächste Schritte kannst du danach ergänzen.",
      proofAria: "Was deine Akte zusammenführt",
      proof: ["Studienplan", "Unterlagen", "Nächste Schritte"],
      cta: "Akte starten",
      login: "Ich habe schon ein Konto",
    },
    footer: {
      tagline: "Deine Studienakte, Schritt für Schritt.",
      independent: "Unabhängige Plattform",
      columns: [
        ["Mein Weg", [["Die sechs Schritte", "#parcours"], ["Hilfreiche Tools", "#outils"], ["Häufige Fragen", "#faq"]]],
        ["Vorbereiten", [["Mein Bereich", "/login"], ["Studiengänge vergleichen", "#programmes"], ["Akte starten", "/signup"]]],
        ["Hilfreiche Links", [["Anmelden", "/login"], ["uni-assist · externe Quelle", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo organisiert deine Vorbereitung. Über Zulassung, Visum und andere offizielle Fragen entscheiden die zuständigen Stellen.",
      photoCredit1: "Illustrationsfotos:",
      photoCredit2: "Die abgebildeten Personen werden nicht als Nutzerinnen oder Nutzer von AlmaGo dargestellt.",
    },
  },
  auth: {
    studentSpace: "Studierendenbereich",
    loginStory: {
      eyebrow: "Dein AlmaGo-Bereich",
      title: "Mach bei deinem nächsten Schritt weiter.",
      description: "Deine Studienakte bleibt an einem Ort organisiert.",
      badge: "Deine Akte bleibt übersichtlich",
      points: [
        ["Deine nächste Aktion", "Sieh schnell, was jetzt zu tun ist."],
        ["Deine Unterlagen", "Sieh, was vorhanden ist und was geprüft werden muss."],
        ["Deine Bewerbungen", "Behalte jeden Studiengang an einem Ort im Blick."],
      ],
    },
    signupStory: {
      eyebrow: "Dein Weg beginnt hier",
      title: "Erstelle deinen Bereich.",
      description: "Danach trägst du deinen Studienplan und deine Unterlagen ein.",
      badge: "Studieren in Deutschland – Schritt für Schritt",
      points: [
        ["Konto erstellen", "Deine Anmeldedaten."],
        ["Studienplan festlegen", "Abschluss, Fach, Sprache und Studienstart."],
        ["Akte vorbereiten", "Unterlagen, Studiengänge und Bewerbungen."],
      ],
    },
    boundaryTitle: "AlmaGo hilft dir bei der Vorbereitung.",
    boundaryText: "Hochschulen und Behörden treffen die offiziellen Entscheidungen.",
    titles: {
      login: "Anmelden",
      signup: "Konto erstellen",
      forgot: "Passwort zurücksetzen",
    },
    subtitles: {
      login: "Öffne deine Akte und sieh, was als Nächstes ansteht.",
      signup: "Erstelle deinen Bereich und bereite deine Studienakte für Deutschland vor.",
      forgot: "Gib deine E-Mail-Adresse ein. Wir senden dir einen Link.",
    },
    labels: {
      firstName: "Vorname",
      lastName: "Nachname",
      email: "E-Mail",
      password: "Passwort",
      show: "Anzeigen",
      hide: "Ausblenden",
      studentAccount: "Studierendenkonto",
      minPassword: "Mindestens 8 Zeichen",
      emailConfirmation: "Bestätigung per E-Mail",
      alreadyAccount: "Du hast schon ein Konto?",
      forgotPassword: "Passwort vergessen?",
      backLogin: "Zurück zur Anmeldung",
      createAccount: "Konto erstellen",
      login: "Anmelden",
      signup: "Konto erstellen",
      sendLink: "Link senden",
      loading: "Bitte warten...",
    },
    placeholders: {
      firstName: "Dein Vorname",
      lastName: "Dein Nachname",
      email: "du@beispiel.de",
    },
    messages: {
      resetSent: "Wenn diese E-Mail registriert ist, haben wir einen Link gesendet.",
      checkEmail: "Prüfe deine E-Mails, um fortzufahren.",
      invalidLogin: "E-Mail oder Passwort ist falsch.",
      generic: "Das hat gerade nicht funktioniert. Bitte versuche es noch einmal.",
      signupError: "Das Konto konnte nicht erstellt werden. Prüfe deine Angaben und versuche es erneut.",
      resetError: "Der Link konnte nicht gesendet werden. Bitte versuche es erneut.",
    },
    mobile: {
      signupLink: "Konto erstellen",
      loginLink: "Anmelden",
    },
  },
  shell: {
    studentNameFallback: "Student",
    skip: "Zum Inhalt springen",
    studentFile: "Studierendenakte",
    studyProject: "Studienplan für Deutschland",
    navigation: "Navigation",
    studentNavigation: "Studierenden-Navigation",
    studentMobileNavigation: "Mobile Studierenden-Navigation",
    groups: ["Meine Akte", "Mein Weg", "Ressourcen"],
    items: [
      ["Meine Übersicht", "Alles auf einen Blick"],
      ["Mein Studienplan", "Mein Startpunkt"],
      ["Mein Weg", "Meine Schritte in Deutschland"],
      ["Mein Profil", "Meine Angaben"],
      ["Meine Unterlagen", "Dateien und Status"],
      ["Meine Studiengänge", "Studiengänge zum Vergleichen"],
      ["Sprachkurse", "Kurse zum Vergleichen"],
      ["Finanzierung & Versicherung", "Geprüfte Optionen"],
      ["Meine Schritte", "Was als Nächstes ansteht"],
      ["Meine Bewerbungen", "Stand und Fristen"],
    ],
    footer: "AlmaGo hilft dir bei der Vorbereitung. Offizielle Stellen treffen die Entscheidungen.",
    logout: "Abmelden",
    hello: "Hallo",
    mobileIntro: "Wähle, was du öffnen möchtest.",
    personalFile: "Persönliche Akte",
    desktopIntro: "Hier siehst du deinen nächsten Schritt.",
    openMenu: "Studierendenmenü öffnen",
    closeMenu: "Studierendenmenü schließen",
    menu: "Menü",
    close: "Schließen",
  },
} as const;

export const nativeCopy = { fr, ar, en, de } as const;

export type NativeCopy = (typeof nativeCopy)[Locale];

export function getNativeCopy(locale: Locale): NativeCopy {
  return nativeCopy[locale];
}
