import type { Locale } from "@/lib/i18n";

const fr = {
  metadata: {
    title: "AlmaGo | Études en Allemagne",
    description: "Préparez votre projet d’études en Allemagne avec AlmaGo, étape par étape.",
    keywords: ["études en Allemagne", "dossier étudiant", "programmes Allemagne", "candidatures Allemagne", "AlmaGo"],
  },
  common: {
    language: "Langue",
    homeAria: "AlmaGo accueil",
    skip: "Aller au contenu",
  },
  home: {
    nav: {
      journey: "Le parcours",
      space: "Mon espace",
      why: "Pourquoi AlmaGo",
      questions: "Questions",
      contact: "Contact",
      login: "Se connecter",
      signup: "Créer mon dossier",
      orientation: "Orientation gratuite",
      openMenu: "Ouvrir le menu",
      closeMenu: "Fermer le menu",
      mainNavigation: "Navigation principale",
      mobileNavigation: "Navigation mobile",
    },
    hero: {
      eyebrow: "Étudier en Allemagne, étape par étape.",
      title1: "Votre projet d’études",
      title2: "en Allemagne,",
      title3: "plus clair.",
      lead: "AlmaGo vous aide à préparer votre dossier, comparer des programmes et savoir quoi faire ensuite.",
      primary: "Créer mon dossier",
      orientationPrimary: "Faire mon orientation gratuite",
      secondary: "Voir les étapes",
      proof: ["6 étapes simples", "Documents au même endroit", "Sources officielles à vérifier"],
      exampleAria: "Exemple de dossier AlmaGo",
      exampleTitle: "Votre dossier avance",
      sample: "Exemple",
      rows: [
        ["Mon projet", "Objectif indiqué", "Indiqué"],
        ["Mes documents", "À préparer maintenant", ""],
        ["Mes candidatures", "À suivre", ""],
      ],
    },
    quick: {
      aria: "Accès rapides",
      navAria: "Accès rapide",
      items: [
        ["Comparer les programmes", "Critères et sources officielles"],
        ["Voir les étapes", "Ce qu’il faut faire"],
        ["Préparer mes documents", "Documents à ajouter"],
        ["Préparer mon départ", "Langue, financement, assurance"],
        ["Voir les questions", "Réponses utiles"],
      ],
    },
    photo: {
      eyebrow: "Votre projet d’études d’abord",
      title1: "Préparez la suite",
      title2: "au bon moment.",
      text: "Commencez par le programme et les documents. Préparez ensuite le reste, au bon moment.",
      regionAria: "Étapes du parcours étudiant, faites défiler horizontalement",
      cards: ["Je compare les programmes", "Je prépare mes documents", "Je prépare mes candidatures"],
      alts: [
        "Des étudiantes se déplacent sur un campus avec un ordinateur et des documents.",
        "Des étudiants travaillent ensemble dans une bibliothèque universitaire.",
        "Deux étudiants discutent devant l’entrée d’un établissement universitaire.",
      ],
    },
    journey: {
      eyebrow: "Votre parcours, simplement",
      title1: "Six étapes",
      title2: "pour avancer.",
      intro: "Vous n’avez pas besoin de tout savoir maintenant. Faites une étape à la fois.",
      aria: "Les six étapes de votre projet d’études",
      imageAlts: [
        "Des étudiants consultent des documents devant un bâtiment universitaire.",
        "Des documents et un stylo posés sur un bureau.",
        "Des étudiants marchent devant un campus universitaire moderne.",
        "Des étudiants travaillent ensemble avec un ordinateur et des notes.",
        "Des étudiants travaillent sur des ordinateurs dans une bibliothèque.",
        "Deux étudiants échangent pendant une séance de travail.",
      ],
      steps: [
        ["Définir mon projet", "Choisissez le diplôme, le domaine, la langue et la rentrée qui vous intéressent.", "Mon point de départ"],
        ["Préparer mes documents", "Ajoutez vos diplômes et les documents que vous avez déjà.", "Mes études"],
        ["Comparer les programmes", "Regardez les critères, les dates et la source officielle.", "Mes options"],
        ["Préparer mes candidatures", "Pour chaque programme, voyez les documents et la prochaine action.", "Mes dossiers"],
        ["Préparer le départ", "Voyez ce dont vous aurez besoin selon votre projet.", "Langue, budget, assurance"],
        ["Suivre mes étapes", "Voyez ce qui est fait et ce qu’il reste à faire.", "La suite"],
      ],
      foot: "AlmaGo vous aide à préparer. Les universités et les autorités prennent les décisions.",
      cta: "Commencer mon dossier",
    },
    tools: {
      eyebrow: "Pour avancer",
      title: "Choisissez par où commencer.",
      intro: "Trois façons simples d’avancer dans votre projet.",
      items: [
        ["Voir par où commencer", "Indiquez votre diplôme, votre domaine, votre langue et votre rentrée.", "Commencer mon dossier"],
        ["Comparer les programmes", "Regardez les critères, les dates et la source officielle.", "Voir les programmes"],
        ["Vérifier une information", "Voyez qui donne l’information et où la confirmer.", "Voir les sources"],
      ],
    },
    faq: {
      eyebrow: "Questions utiles",
      title1: "Avant de faire",
      title2: "le premier pas.",
      intro: "Les réponses aux questions les plus fréquentes.",
      cta: "Voir les étapes",
      items: [
        ["Puis-je commencer sans admission ?", "Oui. Commencez par votre projet et les documents que vous avez. Cherchez ensuite une admission adaptée avant les démarches qui en dépendent."],
        ["Que vais-je retrouver dans mon espace ?", "Votre projet, vos documents, vos programmes, vos candidatures et vos prochaines étapes."],
        ["AlmaGo dépose-t-il mes candidatures ?", "Non. AlmaGo vous aide à préparer et suivre vos candidatures. Vous les envoyez par le canal demandé par l’université, par exemple directement ou via uni-assist."],
        ["Les informations sont-elles officielles ?", "AlmaGo indique la source et la date de contrôle quand elles sont disponibles. Vérifiez toujours la source officielle avant une démarche."],
        ["AlmaGo garantit-il une admission ou un visa ?", "Non. AlmaGo organise votre préparation. Les universités, ambassades et autorités prennent les décisions."],
      ],
    },
    closing: {
      eyebrow: "Commencez simplement",
      title1: "Commencez",
      title2: "par votre projet.",
      text: "Créez votre dossier. Vous ajouterez vos documents et vos prochaines étapes ensuite.",
      proofAria: "Ce que votre dossier rassemble",
      proof: ["Projet", "Documents", "Prochaines étapes"],
      cta: "Créer mon dossier",
      login: "J’ai déjà un compte",
    },
    footer: {
      tagline: "Votre dossier d’études, étape par étape.",
      independent: "Plateforme indépendante",
      columns: [
        ["Parcours", [["Les six étapes", "#parcours"], ["Outils utiles", "#outils"], ["Questions fréquentes", "#faq"]]],
        ["Préparer", [["Mon espace", "/login"], ["Comparer les programmes", "#programmes"], ["Créer mon dossier", "/signup"]]],
        ["Repères", [["Contact", "/contact"], ["Mentions légales", "/legal/imprint"], ["Confidentialité", "/legal/privacy"], ["Conditions d’utilisation", "/legal/terms"], ["Se connecter", "/login"], ["uni-assist · source externe", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo organise votre préparation. Les admissions, visas et autres décisions officielles appartiennent aux organismes compétents.",
      photoCredit1: "Photographies d’illustration :",
      photoCredit2: "Les personnes représentées ne sont pas présentées comme utilisatrices d’AlmaGo.",
    },
  },
  auth: {
    studentSpace: "Espace étudiant",
    loginStory: {
      eyebrow: "Votre espace AlmaGo",
      title: "Retrouvez votre prochaine étape.",
      description: "Votre dossier reste au même endroit.",
      badge: "Votre dossier reste organisé",
      points: [
        ["Votre prochaine action", "Voyez rapidement ce qu’il faut faire."],
        ["Vos documents", "Retrouvez ce qui est ajouté ou à vérifier."],
        ["Vos candidatures", "Suivez chaque programme au même endroit."],
      ],
    },
    signupStory: {
      eyebrow: "Votre parcours commence ici",
      title: "Créez votre espace.",
      description: "Vous indiquerez ensuite votre projet et vos documents.",
      badge: "Étudier en Allemagne, étape par étape",
      points: [
        ["Créer votre compte", "Vos informations de connexion."],
        ["Définir votre projet", "Diplôme, domaine, langue et rentrée."],
        ["Préparer votre dossier", "Documents, programmes et candidatures."],
      ],
    },
    boundaryTitle: "AlmaGo vous aide à préparer.",
    boundaryText: "Les universités et les autorités prennent les décisions officielles.",
    titles: {
      login: "Se connecter",
      signup: "Créer mon compte",
      forgot: "Réinitialiser mon mot de passe",
    },
    subtitles: {
      login: "Retrouvez votre dossier et votre prochaine étape.",
      signup: "Créez votre espace pour préparer votre dossier Allemagne.",
      forgot: "Indiquez votre email pour recevoir un lien.",
    },
    labels: {
      firstName: "Prénom",
      lastName: "Nom",
      email: "Email",
      password: "Mot de passe",
      show: "Afficher",
      hide: "Masquer",
      studentAccount: "Compte étudiant",
      minPassword: "8 caractères minimum",
      emailConfirmation: "Confirmation par email",
      alreadyAccount: "Déjà un compte ?",
      forgotPassword: "Mot de passe oublié ?",
      backLogin: "Retour à la connexion",
      createAccount: "Créer un compte",
      login: "Se connecter",
      signup: "Créer mon compte",
      sendLink: "Envoyer le lien",
      loading: "Patientez...",
    },
    placeholders: {
      firstName: "Votre prénom",
      lastName: "Votre nom",
      email: "vous@exemple.com",
    },
    messages: {
      resetSent: "Si cette adresse existe, un lien de réinitialisation a été envoyé.",
      checkEmail: "Vérifiez votre adresse email pour continuer.",
      invalidLogin: "Email ou mot de passe incorrect.",
      generic: "Impossible de continuer pour le moment. Réessayez.",
      signupError: "Impossible de créer le compte pour le moment. Vérifiez vos informations et réessayez.",
      resetError: "Impossible d’envoyer le lien pour le moment. Réessayez.",
    },
    mobile: {
      signupLink: "Créer un compte",
      loginLink: "Connexion",
    },
  },
  shell: {
    studentNameFallback: "étudiant",
    skip: "Aller au contenu",
    studentFile: "Dossier étudiant",
    studyProject: "Projet d’études en Allemagne",
    navigation: "Navigation",
    studentNavigation: "Navigation étudiant",
    studentMobileNavigation: "Navigation étudiant mobile",
    groups: ["Dossier", "Parcours", "Ressources"],
    items: [
      ["Mon dossier", "Vue d’ensemble"],
      ["Mon projet", "Point de départ"],
      ["Mon parcours", "Mes étapes en Allemagne"],
      ["Mon profil", "Mes informations"],
      ["Mes documents", "Pièces et statuts"],
      ["Mes programmes", "Programmes à comparer"],
      ["Cours de langue", "Cours à comparer"],
      ["Financement & assurance", "Options vérifiées"],
      ["Mes démarches", "Étapes du dossier"],
      ["Mes candidatures", "Suivi et échéances"],
    ],
    footer: "AlmaGo vous aide à préparer. Les organismes officiels prennent les décisions.",
    logout: "Déconnexion",
    hello: "Bonjour",
    mobileIntro: "Choisissez ce que vous voulez consulter.",
    personalFile: "Dossier personnel",
    desktopIntro: "Retrouvez ici votre prochaine étape.",
    openMenu: "Ouvrir le menu étudiant",
    closeMenu: "Fermer le menu étudiant",
    menu: "Menu",
    close: "Fermer",
  },
} as const;

const ar = {
  metadata: {
    title: "AlmaGo | الدراسة في ألمانيا",
    description: "يساعدك AlmaGo على تنظيم طريقك للدراسة في ألمانيا بخطوات واضحة.",
    keywords: ["الدراسة في ألمانيا", "ملف الطالب", "برامج الدراسة في ألمانيا", "التقديم للجامعات الألمانية", "AlmaGo"],
  },
  common: {
    language: "اللغة",
    homeAria: "الصفحة الرئيسية لـ AlmaGo",
    skip: "الانتقال إلى المحتوى",
  },
  home: {
    nav: {
      journey: "المسار",
      space: "ملفي",
      why: "لماذا AlmaGo؟",
      questions: "الأسئلة",
      contact: "تواصل معنا",
      login: "تسجيل الدخول",
      signup: "أنشئ ملفك",
      orientation: "توجيه مجاني",
      openMenu: "فتح القائمة",
      closeMenu: "إغلاق القائمة",
      mainNavigation: "القائمة الرئيسية",
      mobileNavigation: "قائمة الهاتف",
    },
    hero: {
      eyebrow: "طريقك إلى الدراسة في ألمانيا.",
      title1: "خطّط لدراستك",
      title2: "في ألمانيا",
      title3: "خطوة بخطوة.",
      lead: "قارن البرامج، رتّب مستنداتك، واعرف ما عليك فعله بعد ذلك — في مكان واحد.",
      primary: "أنشئ ملفك",
      orientationPrimary: "ابدأ توجيهي المجاني",
      secondary: "اكتشف الخطوات",
      proof: ["6 خطوات واضحة", "مستنداتك في مكان واحد", "مصادر رسمية للتحقق"],
      exampleAria: "مثال على ملف AlmaGo",
      exampleTitle: "ملفك في لمحة",
      sample: "مثال",
      rows: [
        ["هدفك الدراسي", "تم تحديده", "جاهز"],
        ["مستنداتك", "ما الذي ينقص؟", ""],
        ["طلبات التقديم", "تابع تقدّمها", ""],
      ],
    },
    quick: {
      aria: "وصول سريع",
      navAria: "روابط سريعة",
      items: [
        ["قارن البرامج", "الشروط والمصادر الرسمية"],
        ["اعرف خطوتك التالية", "ماذا تفعل الآن؟"],
        ["جهّز مستنداتك", "ما الذي تحتاجه؟"],
        ["استعد للسفر", "اللغة والتمويل والتأمين"],
        ["الأسئلة الشائعة", "إجابات سريعة"],
      ],
    },
    photo: {
      eyebrow: "ابدأ بالأهم",
      title1: "رتّب خطواتك",
      title2: "من البداية.",
      text: "ابدأ باختيار البرنامج، ثم جهّز مستنداتك وطلباتك في الوقت المناسب.",
      regionAria: "مراحل مشروع الطالب، مرّر أفقيًا",
      cards: ["قارن البرامج", "جهّز مستنداتك", "حضّر طلباتك"],
      alts: [
        "طالبات في الحرم الجامعي يحملن حاسوبًا ومستندات.",
        "طلاب يعملون معًا في مكتبة جامعية.",
        "طالبان يتحدثان أمام مبنى جامعي.",
      ],
    },
    journey: {
      eyebrow: "مسار واضح",
      title1: "ست خطوات",
      title2: "من البداية إلى التقديم.",
      intro: "لا تحتاج إلى إنهاء كل شيء دفعة واحدة. ركّز على خطوة واحدة في كل مرة.",
      aria: "الخطوات الست لمشروع الدراسة",
      imageAlts: [
        "طلاب يراجعون مستندات أمام مبنى جامعي.",
        "مستندات وقلم على مكتب.",
        "طلاب يسيرون أمام حرم جامعي حديث.",
        "طلاب يعملون معًا باستخدام حاسوب وملاحظات.",
        "طلاب يعملون على حواسيب في مكتبة.",
        "طالبان يتحدثان أثناء جلسة دراسة.",
      ],
      steps: [
        ["حدّد هدفك", "اختر الشهادة والمجال واللغة وموعد بدء الدراسة.", "ابدأ من هنا"],
        ["جهّز مستنداتك", "أضف شهاداتك والمستندات المتوفرة لديك.", "مستنداتك"],
        ["قارن البرامج", "تحقق من الشروط والمواعيد والمصدر الرسمي قبل الاختيار.", "برامجك"],
        ["حضّر طلباتك", "اعرف ما يطلبه كل برنامج وما الخطوة التالية.", "التقديم"],
        ["استعد للسفر", "راجع اللغة والتمويل والتأمين وما ينطبق على حالتك.", "قبل السفر"],
        ["تابع تقدّمك", "اطّلع على ما أنجزته وما بقي عليك.", "التالي"],
      ],
      foot: "يساعدك AlmaGo على التحضير. القرارات الرسمية تتخذها الجامعات والجهات المختصة.",
      cta: "أنشئ ملفك",
    },
    tools: {
      eyebrow: "ابدأ من حيث أنت",
      title: "اختر نقطة البداية المناسبة لك.",
      intro: "أخبرنا بوضعك، قارن البرامج، أو تحقق من معلومة قبل أن تعتمد عليها.",
      items: [
        ["أخبرنا بوضعك", "أدخل شهادتك ومجالك ومستواك اللغوي وموعد البدء.", "أنشئ ملفك"],
        ["قارن البرامج", "اطّلع على الشروط والمواعيد والمصدر الرسمي.", "استعرض البرامج"],
        ["تحقق من معلومة", "اعرف مصدر المعلومة وأين يمكنك التأكد منها.", "اعرض المصادر"],
      ],
    },
    faq: {
      eyebrow: "أسئلة شائعة",
      title1: "قبل أن تبدأ،",
      title2: "إجابات سريعة.",
      intro: "أهم ما تحتاج إلى معرفته في البداية.",
      cta: "استعرض الخطوات",
      items: [
        ["هل يمكنني البدء من دون قبول جامعي؟", "نعم. يمكنك البدء بتحديد هدفك وتجهيز ما لديك من مستندات، ثم البحث عن قبول مناسب قبل الخطوات التي تتطلبه."],
        ["ماذا سأجد في ملفي؟", "ستجد مشروعك، مستنداتك، البرامج التي تقارنها، طلبات التقديم والخطوات التالية."],
        ["هل يقدّم AlmaGo الطلبات نيابةً عني؟", "لا. يساعدك AlmaGo على تجهيز طلباتك ومتابعتها. أنت ترسل الطلب بالطريقة التي تطلبها الجامعة، مباشرةً أو عبر uni-assist مثلاً."],
        ["هل معلومات AlmaGo رسمية؟", "نوضح المصدر وتاريخ التحقق عندما يتوفران. قبل أي إجراء مهم، ارجع دائمًا إلى المصدر الرسمي."],
        ["هل يضمن AlmaGo القبول أو التأشيرة؟", "لا. AlmaGo يساعدك على التحضير فقط. الجامعة والسفارة والسلطات المختصة هي التي تتخذ القرار."],
      ],
    },
    closing: {
      eyebrow: "ابدأ الآن",
      title1: "أنشئ ملفك.",
      title2: "واعرف خطوتك التالية.",
      text: "ابدأ بالمعلومات التي لديك الآن. يمكنك إضافة مستنداتك ومتابعة بقية الخطوات لاحقًا.",
      proofAria: "محتوى ملفك",
      proof: ["هدفك", "مستنداتك", "خطوتك التالية"],
      cta: "أنشئ ملفك",
      login: "لدي حساب",
    },
    footer: {
      tagline: "رتّب طريقك إلى الدراسة في ألمانيا، خطوة بخطوة.",
      independent: "منصة مستقلة",
      columns: [
        ["المسار", [["الخطوات الست", "#parcours"], ["أدوات مفيدة", "#outils"], ["الأسئلة الشائعة", "#faq"]]],
        ["التحضير", [["ملفي", "/login"], ["مقارنة البرامج", "#programmes"], ["أنشئ ملفك", "/signup"]]],
        ["روابط مفيدة", [["تواصل معنا", "/contact"], ["المعلومات القانونية", "/legal/imprint"], ["الخصوصية", "/legal/privacy"], ["شروط الاستخدام", "/legal/terms"], ["تسجيل الدخول", "/login"], ["uni-assist · مصدر خارجي", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo ينظم عملية التحضير. القبول والتأشيرة والقرارات الرسمية الأخرى تبقى من اختصاص الجهات المختصة.",
      photoCredit1: "الصور التوضيحية:",
      photoCredit2: "الأشخاص الظاهرون في الصور لا يتم تقديمهم على أنهم مستخدمون لـ AlmaGo.",
    },
  },
  auth: {
    studentSpace: "مساحتي",
    loginStory: {
      eyebrow: "ملفك على AlmaGo",
      title: "سجّل الدخول وتابع من حيث توقفت.",
      description: "ستجد مستنداتك وبرامجك وخطواتك في مكان واحد.",
      badge: "كل شيء في مكان واحد",
      points: [
        ["الخطوة التالية", "اعرف مباشرة ما الذي عليك فعله."],
        ["مستنداتك", "راجع ما أضفته وما يحتاج إلى تحديث."],
        ["طلباتك", "تابع برامجك وطلبات التقديم بسهولة."],
      ],
    },
    signupStory: {
      eyebrow: "ابدأ من هنا",
      title: "أنشئ حسابك وابدأ.",
      description: "بعد إنشاء الحساب، نساعدك على تحديد هدفك وتجهيز ملفك خطوة بخطوة.",
      badge: "طريق أوضح للدراسة في ألمانيا",
      points: [
        ["أنشئ حسابك", "ابدأ ببيانات الدخول الأساسية."],
        ["حدّد هدفك", "اختر الشهادة والمجال واللغة وموعد البداية."],
        ["جهّز ملفك", "أضف مستنداتك وقارن البرامج وتابع طلباتك."],
      ],
    },
    boundaryTitle: "AlmaGo يساعدك على تنظيم ملفك.",
    boundaryText: "الجامعات والسلطات المختصة هي التي تتخذ القرارات الرسمية.",
    titles: {
      login: "تسجيل الدخول",
      signup: "إنشاء حساب",
      forgot: "إعادة تعيين كلمة المرور",
    },
    subtitles: {
      login: "ارجع إلى ملفك وتابع من حيث توقفت.",
      signup: "أنشئ حسابك وابدأ تجهيز ملفك للدراسة في ألمانيا.",
      forgot: "أدخل بريدك الإلكتروني لنرسل لك رابطًا.",
    },
    labels: {
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      show: "إظهار",
      hide: "إخفاء",
      studentAccount: "حساب طالب",
      minPassword: "8 أحرف على الأقل",
      emailConfirmation: "تأكيد عبر البريد الإلكتروني",
      alreadyAccount: "لديك حساب بالفعل؟",
      forgotPassword: "نسيت كلمة المرور؟",
      backLogin: "العودة إلى تسجيل الدخول",
      createAccount: "إنشاء حساب",
      login: "تسجيل الدخول",
      signup: "إنشاء حساب",
      sendLink: "إرسال الرابط",
      loading: "يرجى الانتظار...",
    },
    placeholders: {
      firstName: "اسمك الأول",
      lastName: "اسم العائلة",
      email: "you@example.com",
    },
    messages: {
      resetSent: "إذا كان هذا البريد مسجّلًا، فقد أرسلنا رابط إعادة التعيين.",
      checkEmail: "تحقق من بريدك الإلكتروني للمتابعة.",
      invalidLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      generic: "تعذر إكمال العملية الآن. حاول مرة أخرى.",
      signupError: "تعذر إنشاء الحساب الآن. تحقق من بياناتك وحاول مرة أخرى.",
      resetError: "تعذر إرسال الرابط الآن. حاول مرة أخرى.",
    },
    mobile: {
      signupLink: "إنشاء حساب",
      loginLink: "تسجيل الدخول",
    },
  },
  shell: {
    studentNameFallback: "طالب",
    skip: "الانتقال إلى المحتوى",
    studentFile: "ملف الطالب",
    studyProject: "مشروع الدراسة في ألمانيا",
    navigation: "التنقل",
    studentNavigation: "قائمة الطالب",
    studentMobileNavigation: "قائمة الطالب على الهاتف",
    groups: ["ملفي", "خطواتي", "الموارد"],
    items: [
      ["ملفي", "نظرة عامة"],
      ["مشروعي", "نقطة البداية"],
      ["مساري", "خطواتي في ألمانيا"],
      ["بياناتي", "معلوماتي"],
      ["مستنداتي", "المستندات وحالتها"],
      ["برامجي", "برامج للمقارنة"],
      ["دورات اللغة", "دورات ومصادرها"],
      ["التمويل والتأمين", "خيارات ومصادر"],
      ["خطواتي", "ما عليك فعله"],
      ["طلبات التقديم", "الحالة والمواعيد"],
    ],
    footer: "AlmaGo يساعدك على التحضير. الجهات الرسمية هي التي تتخذ القرارات.",
    logout: "تسجيل الخروج",
    hello: "مرحبًا",
    mobileIntro: "اختر ما تريد الاطلاع عليه.",
    personalFile: "ملفي الشخصي",
    desktopIntro: "هنا تجد أهم ما يخص ملفك وخطوتك التالية.",
    openMenu: "فتح قائمة الطالب",
    closeMenu: "إغلاق قائمة الطالب",
    menu: "القائمة",
    close: "إغلاق",
  },
} as const;

const en = {
  metadata: {
    title: "AlmaGo | Study in Germany",
    description: "Plan your studies in Germany with AlmaGo, one clear step at a time.",
    keywords: ["study in Germany", "student application", "German university programmes", "Germany applications", "AlmaGo"],
  },
  common: {
    language: "Language",
    homeAria: "AlmaGo home",
    skip: "Skip to content",
  },
  home: {
    nav: {
      journey: "Your journey",
      space: "My workspace",
      why: "Why AlmaGo",
      questions: "Questions",
      contact: "Contact",
      login: "Sign in",
      signup: "Get started",
      orientation: "Free orientation",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      mainNavigation: "Main navigation",
      mobileNavigation: "Mobile navigation",
    },
    hero: {
      eyebrow: "Your route to studying in Germany.",
      title1: "Plan your studies",
      title2: "in Germany",
      title3: "with a clear next step.",
      lead: "Compare programmes, organise your documents, and always know what to do next with AlmaGo.",
      primary: "Get started",
      orientationPrimary: "Start my free orientation",
      secondary: "Explore the steps",
      proof: ["6 practical steps", "Your documents in one place", "Official sources when they matter"],
      exampleAria: "Example AlmaGo file",
      exampleTitle: "Your study plan at a glance",
      sample: "Example",
      rows: [
        ["Study plan", "Goal set", "Ready"],
        ["Documents", "Next item to prepare", ""],
        ["Applications", "Track progress", ""],
      ],
    },
    quick: {
      aria: "Quick access",
      navAria: "Quick links",
      items: [
        ["Compare programmes", "Requirements and official sources"],
        ["Explore the steps", "What to do next"],
        ["Organise my documents", "What to prepare"],
        ["Prepare for Germany", "Language, funding and insurance"],
        ["Read common questions", "Useful answers"],
      ],
    },
    photo: {
      eyebrow: "Start with what matters now",
      title1: "Prepare each step",
      title2: "when you need it.",
      text: "Choose a programme, organise the documents you have, and prepare the rest when it becomes relevant.",
      regionAria: "Student journey steps, scroll horizontally",
      cards: ["Compare programmes", "Organise documents", "Prepare applications"],
      alts: [
        "Students walking across a campus with a laptop and documents.",
        "Students working together in a university library.",
        "Two students talking outside a university building.",
      ],
    },
    journey: {
      eyebrow: "A clear route from plan to application",
      title1: "Six practical steps",
      title2: "from plan to application.",
      intro: "You do not need to figure everything out at once. Focus on one useful step at a time.",
      aria: "Six steps in your study journey",
      imageAlts: [
        "Students reviewing documents outside a university building.",
        "Documents and a pen on a desk.",
        "Students walking outside a modern university campus.",
        "Students working together with a laptop and notes.",
        "Students working on laptops in a library.",
        "Two students talking during a study session.",
      ],
      steps: [
        ["Set your goal", "Choose the degree, subject, language and intake that fit your plan.", "Start here"],
        ["Organise your documents", "Add your qualifications and the documents you already have.", "Your documents"],
        ["Compare programmes", "Check requirements, deadlines and the official source before you choose.", "Your options"],
        ["Prepare applications", "Review what each programme requires and what to do next.", "Applications"],
        ["Prepare for Germany", "Review the language, budget, insurance and other steps that apply to your situation.", "Before you travel"],
        ["Track your progress", "See what is done and what still needs your attention.", "Next step"],
      ],
      foot: "AlmaGo helps you prepare. Universities and public authorities make the official decisions.",
      cta: "Get started",
    },
    tools: {
      eyebrow: "Choose your starting point",
      title: "Start where it makes sense for you.",
      intro: "Start with your situation, compare programmes, or check the information you need.",
      items: [
        ["Tell us your situation", "Add your qualification, subject, language level and preferred intake.", "Get started"],
        ["Compare programmes", "Check requirements, deadlines and the official source.", "See programmes"],
        ["Check information", "See where information comes from and where to verify it.", "See sources"],
      ],
    },
    faq: {
      eyebrow: "Useful questions",
      title1: "Before you start,",
      title2: "here are the essentials.",
      intro: "Clear answers to common questions before you get started.",
      cta: "See the steps",
      items: [
        ["Can I start without an admission offer?", "Yes. Start with your plan and the documents you already have. Then look for a suitable admission route before steps that depend on it."],
        ["What will I find in my space?", "Your study plan, documents, programmes, applications and next steps."],
        ["Does AlmaGo submit applications for me?", "No. AlmaGo helps you prepare and track them. You submit through the route required by the university, for example directly or through uni-assist."],
        ["Is the information official?", "AlmaGo shows the source and review date when available. Always check the official source before taking action."],
        ["Does AlmaGo guarantee admission or a visa?", "No. AlmaGo helps you prepare. Universities, embassies and public authorities make the decisions."],
      ],
    },
    closing: {
      eyebrow: "Ready to begin?",
      title1: "Build your",
      title2: "study plan.",
      text: "Create your account, add the documents you have, and work through the next steps at your own pace.",
      proofAria: "What your file brings together",
      proof: ["Study plan", "Documents", "Next steps"],
      cta: "Get started",
      login: "I already have an account",
    },
    footer: {
      tagline: "A clearer path to studying in Germany.",
      independent: "Independent platform",
      columns: [
        ["Journey", [["The six steps", "#parcours"], ["Useful tools", "#outils"], ["Common questions", "#faq"]]],
        ["Prepare", [["My workspace", "/login"], ["Compare programmes", "#programmes"], ["Get started", "/signup"]]],
        ["Useful links", [["Contact", "/contact"], ["Legal notice", "/legal/imprint"], ["Privacy", "/legal/privacy"], ["Terms of use", "/legal/terms"], ["Sign in", "/login"], ["uni-assist · external source", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo organises your preparation. Admission, visa and other official decisions remain with the responsible authorities.",
      photoCredit1: "Illustration photos:",
      photoCredit2: "People shown in these photos are not presented as AlmaGo users.",
    },
  },
  auth: {
    studentSpace: "Student workspace",
    loginStory: {
      eyebrow: "Your AlmaGo workspace",
      title: "Sign in and continue where you left off.",
      description: "Your documents, programmes and next steps stay organised in one place.",
      badge: "Everything in one place",
      points: [
        ["Your next step", "See what needs your attention now."],
        ["Your documents", "See what you have added and what still needs attention."],
        ["Your applications", "Follow each application in one place."],
      ],
    },
    signupStory: {
      eyebrow: "Start here",
      title: "Create your account and get started.",
      description: "Set your study goal, add your documents, and work through the next steps.",
      badge: "A clearer path to studying in Germany",
      points: [
        ["Create your account", "Start with the details you need to sign in."],
        ["Set your goal", "Choose your degree, subject, language and intake."],
        ["Build your workspace", "Bring together documents, programmes and applications."],
      ],
    },
    boundaryTitle: "AlmaGo helps you prepare.",
    boundaryText: "Universities and public authorities make the official decisions.",
    titles: {
      login: "Sign in",
      signup: "Create my account",
      forgot: "Reset my password",
    },
    subtitles: {
      login: "Open your file and see what to do next.",
      signup: "Create your account and start building your study plan for Germany.",
      forgot: "Enter your email and we will send you a reset link.",
    },
    labels: {
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      password: "Password",
      show: "Show",
      hide: "Hide",
      studentAccount: "Student account",
      minPassword: "At least 8 characters",
      emailConfirmation: "Email confirmation",
      alreadyAccount: "Already have an account?",
      forgotPassword: "Forgot your password?",
      backLogin: "Back to sign in",
      createAccount: "Create an account",
      login: "Sign in",
      signup: "Create my account",
      sendLink: "Send reset link",
      loading: "Please wait...",
    },
    placeholders: {
      firstName: "Your first name",
      lastName: "Your last name",
      email: "you@example.com",
    },
    messages: {
      resetSent: "If this email is registered, we have sent a reset link.",
      checkEmail: "Check your email to continue.",
      invalidLogin: "Email or password is incorrect.",
      generic: "We could not complete this right now. Please try again.",
      signupError: "We could not create the account. Check your details and try again.",
      resetError: "We could not send the reset link. Please try again.",
    },
    mobile: {
      signupLink: "Create account",
      loginLink: "Sign in",
    },
  },
  shell: {
    studentNameFallback: "student",
    skip: "Skip to content",
    studentFile: "Student workspace",
    studyProject: "Study plans for Germany",
    navigation: "Navigation",
    studentNavigation: "Student navigation",
    studentMobileNavigation: "Student mobile navigation",
    groups: ["My workspace", "My journey", "Resources"],
    items: [
      ["Dashboard", "At a glance"],
      ["Study plan", "Start here"],
      ["My journey", "My steps in Germany"],
      ["Profile", "My information"],
      ["Documents", "Files and status"],
      ["Programmes", "Compare your options"],
      ["Language courses", "Courses to compare"],
      ["Funding & insurance", "Checked options"],
      ["Next steps", "What to do next"],
      ["Applications", "Progress and deadlines"],
    ],
    footer: "AlmaGo helps you prepare. Official bodies make the decisions.",
    logout: "Sign out",
    hello: "Hello",
    mobileIntro: "Choose what you want to open.",
    personalFile: "My workspace",
    desktopIntro: "See what needs your attention next.",
    openMenu: "Open student menu",
    closeMenu: "Close student menu",
    menu: "Menu",
    close: "Close",
  },
} as const;

const de = {
  metadata: {
    title: "AlmaGo | Studium in Deutschland",
    description: "Plane dein Studium in Deutschland mit AlmaGo – Schritt für Schritt.",
    keywords: ["Studium in Deutschland", "Bewerbung Studium", "Studiengänge Deutschland", "Uni Bewerbung Deutschland", "AlmaGo"],
  },
  common: {
    language: "Sprache",
    homeAria: "AlmaGo Startseite",
    skip: "Zum Inhalt springen",
  },
  home: {
    nav: {
      journey: "Mein Weg",
      space: "Mein Bereich",
      why: "Warum AlmaGo",
      questions: "Fragen",
      contact: "Kontakt",
      login: "Anmelden",
      signup: "Jetzt starten",
      orientation: "Kostenlose Orientierung",
      openMenu: "Menü öffnen",
      closeMenu: "Menü schließen",
      mainNavigation: "Hauptnavigation",
      mobileNavigation: "Mobile Navigation",
    },
    hero: {
      eyebrow: "Dein Weg zum Studium in Deutschland.",
      title1: "Plane dein Studium",
      title2: "in Deutschland",
      title3: "Schritt für Schritt.",
      lead: "Vergleiche Studiengänge, ordne deine Unterlagen und sieh jederzeit, was als Nächstes ansteht.",
      primary: "Jetzt starten",
      orientationPrimary: "Kostenlose Orientierung starten",
      secondary: "Schritte ansehen",
      proof: ["6 praktische Schritte", "Unterlagen an einem Ort", "Offizielle Quellen, wenn es wichtig ist"],
      exampleAria: "Beispiel für eine AlmaGo-Akte",
      exampleTitle: "Dein Studienplan auf einen Blick",
      sample: "Beispiel",
      rows: [
        ["Studienplan", "Ziel festgelegt", "Bereit"],
        ["Unterlagen", "Nächstes Dokument", ""],
        ["Bewerbungen", "Fortschritt verfolgen", ""],
      ],
    },
    quick: {
      aria: "Schnellzugriff",
      navAria: "Schnellzugriff",
      items: [
        ["Studiengänge vergleichen", "Voraussetzungen und offizielle Quellen"],
        ["Schritte ansehen", "Was als Nächstes ansteht"],
        ["Unterlagen ordnen", "Was du vorbereiten solltest"],
        ["Für Deutschland vorbereiten", "Sprache, Finanzierung, Versicherung"],
        ["Häufige Fragen", "Kurze Antworten"],
      ],
    },
    photo: {
      eyebrow: "Konzentriere dich auf den nächsten Schritt",
      title1: "Bereite jeden Schritt",
      title2: "zum passenden Zeitpunkt vor.",
      text: "Wähle einen passenden Studiengang, ordne deine vorhandenen Unterlagen und kümmere dich um den Rest, wenn er relevant wird.",
      regionAria: "Schritte im Studienweg, horizontal scrollen",
      cards: ["Studiengänge vergleichen", "Unterlagen ordnen", "Bewerbungen vorbereiten"],
      alts: [
        "Studierende gehen mit Laptop und Unterlagen über einen Campus.",
        "Studierende arbeiten gemeinsam in einer Hochschulbibliothek.",
        "Zwei Studierende sprechen vor einem Hochschulgebäude.",
      ],
    },
    journey: {
      eyebrow: "Ein klarer Weg von der Planung zur Bewerbung",
      title1: "Sechs praktische Schritte",
      title2: "von der Planung zur Bewerbung.",
      intro: "Du musst nicht alles auf einmal klären. Konzentriere dich auf einen sinnvollen Schritt nach dem anderen.",
      aria: "Sechs Schritte deines Studienwegs",
      imageAlts: [
        "Studierende prüfen Unterlagen vor einem Hochschulgebäude.",
        "Unterlagen und ein Stift auf einem Schreibtisch.",
        "Studierende gehen vor einem modernen Hochschulcampus.",
        "Studierende arbeiten gemeinsam mit Laptop und Notizen.",
        "Studierende arbeiten mit Laptops in einer Bibliothek.",
        "Zwei Studierende sprechen während einer Lernsitzung.",
      ],
      steps: [
        ["Ziel festlegen", "Wähle Abschluss, Fach, Sprache und den Studienstart, der zu deinem Plan passt.", "Hier starten"],
        ["Unterlagen ordnen", "Füge deine Abschlüsse und die Unterlagen hinzu, die du bereits hast.", "Deine Unterlagen"],
        ["Studiengänge vergleichen", "Prüfe Voraussetzungen, Fristen und die offizielle Quelle, bevor du dich entscheidest.", "Deine Optionen"],
        ["Bewerbungen vorbereiten", "Prüfe für jeden Studiengang, was benötigt wird und was als Nächstes ansteht.", "Bewerbungen"],
        ["Für Deutschland vorbereiten", "Prüfe Sprache, Budget, Versicherung und weitere Schritte, die für deine Situation relevant sind.", "Vor der Reise"],
        ["Fortschritt verfolgen", "Sieh, was erledigt ist und was noch deine Aufmerksamkeit braucht.", "Nächster Schritt"],
      ],
      foot: "AlmaGo hilft dir bei der Vorbereitung. Hochschulen und Behörden treffen die offiziellen Entscheidungen.",
      cta: "Jetzt starten",
    },
    tools: {
      eyebrow: "Wähle deinen Startpunkt",
      title: "Starte dort, wo es für dich passt.",
      intro: "Starte mit deiner Situation, vergleiche Studiengänge oder prüfe die Informationen, die du brauchst.",
      items: [
        ["Deine Situation angeben", "Trage Abschluss, Fach, Sprachniveau und gewünschten Studienstart ein.", "Jetzt starten"],
        ["Studiengänge vergleichen", "Prüfe Voraussetzungen, Fristen und die offizielle Quelle.", "Studiengänge ansehen"],
        ["Informationen prüfen", "Sieh, woher eine Information kommt und wo du sie bestätigen kannst.", "Quellen ansehen"],
      ],
    },
    faq: {
      eyebrow: "Wichtige Fragen",
      title1: "Bevor du loslegst,",
      title2: "das Wichtigste auf einen Blick.",
      intro: "Klare Antworten auf häufige Fragen vor dem Start.",
      cta: "Schritte ansehen",
      items: [
        ["Kann ich ohne Zulassung anfangen?", "Ja. Starte mit deinem Studienplan und den Unterlagen, die du schon hast. Suche danach eine passende Zulassungsmöglichkeit, bevor du Schritte machst, die davon abhängen."],
        ["Was finde ich in meinem Bereich?", "Deinen Studienplan, Unterlagen, Studiengänge, Bewerbungen und nächsten Schritte."],
        ["Schickt AlmaGo meine Bewerbungen ab?", "Nein. AlmaGo hilft dir beim Vorbereiten und Nachverfolgen. Du reichst die Bewerbung über den von der Hochschule verlangten Weg ein, zum Beispiel direkt oder über uni-assist."],
        ["Sind die Informationen offiziell?", "AlmaGo zeigt Quelle und Prüfdatum, wenn sie verfügbar sind. Prüfe wichtige Angaben immer noch einmal bei der offiziellen Stelle."],
        ["Garantiert AlmaGo Zulassung oder Visum?", "Nein. AlmaGo hilft bei der Vorbereitung. Hochschulen, Botschaften und Behörden treffen die Entscheidungen."],
      ],
    },
    closing: {
      eyebrow: "Bereit für den Start?",
      title1: "Lege deinen",
      title2: "Studienplan an.",
      text: "Erstelle dein Konto, füge deine vorhandenen Unterlagen hinzu und arbeite die nächsten Schritte in deinem Tempo ab.",
      proofAria: "Was deine Akte zusammenführt",
      proof: ["Studienplan", "Unterlagen", "Nächste Schritte"],
      cta: "Jetzt starten",
      login: "Ich habe schon ein Konto",
    },
    footer: {
      tagline: "Ein klarerer Weg zum Studium in Deutschland.",
      independent: "Unabhängige Plattform",
      columns: [
        ["Mein Weg", [["Die sechs Schritte", "#parcours"], ["Hilfreiche Tools", "#outils"], ["Häufige Fragen", "#faq"]]],
        ["Vorbereiten", [["Mein Bereich", "/login"], ["Studiengänge vergleichen", "#programmes"], ["Jetzt starten", "/signup"]]],
        ["Hilfreiche Links", [["Kontakt", "/contact"], ["Impressum", "/legal/imprint"], ["Datenschutz", "/legal/privacy"], ["Nutzungsbedingungen", "/legal/terms"], ["Anmelden", "/login"], ["uni-assist · externe Quelle", "https://www.uni-assist.de/en/"]]],
      ],
      disclaimer: "AlmaGo organisiert deine Vorbereitung. Über Zulassung, Visum und andere offizielle Fragen entscheiden die zuständigen Stellen.",
      photoCredit1: "Illustrationsfotos:",
      photoCredit2: "Die abgebildeten Personen werden nicht als Nutzerinnen oder Nutzer von AlmaGo dargestellt.",
    },
  },
  auth: {
    studentSpace: "Studierendenbereich",
    loginStory: {
      eyebrow: "Dein Bereich bei AlmaGo",
      title: "Melde dich an und mach dort weiter, wo du aufgehört hast.",
      description: "Unterlagen, Studiengänge und nächste Schritte bleiben an einem Ort organisiert.",
      badge: "Alles an einem Ort",
      points: [
        ["Dein nächster Schritt", "Sieh direkt, was jetzt deine Aufmerksamkeit braucht."],
        ["Deine Unterlagen", "Sieh, was du schon hinzugefügt hast und was noch geprüft werden muss."],
        ["Deine Bewerbungen", "Verfolge deine Bewerbungen an einem Ort."],
      ],
    },
    signupStory: {
      eyebrow: "Hier geht es los",
      title: "Konto erstellen und loslegen.",
      description: "Lege dein Studienziel fest, füge Unterlagen hinzu und arbeite die nächsten Schritte ab.",
      badge: "Ein klarerer Weg zum Studium in Deutschland",
      points: [
        ["Konto erstellen", "Starte mit deinen Anmeldedaten."],
        ["Ziel festlegen", "Wähle Abschluss, Fach, Sprache und Studienstart."],
        ["Bereich aufbauen", "Ordne Unterlagen, Studiengänge und Bewerbungen an einem Ort."],
      ],
    },
    boundaryTitle: "AlmaGo hilft dir bei der Vorbereitung.",
    boundaryText: "Hochschulen und Behörden treffen die offiziellen Entscheidungen.",
    titles: {
      login: "Anmelden",
      signup: "Konto erstellen",
      forgot: "Passwort zurücksetzen",
    },
    subtitles: {
      login: "Öffne deine Akte und sieh, was als Nächstes ansteht.",
      signup: "Erstelle dein Konto und plane Schritt für Schritt dein Studium in Deutschland.",
      forgot: "Gib deine E-Mail-Adresse ein. Wir senden dir einen Link.",
    },
    labels: {
      firstName: "Vorname",
      lastName: "Nachname",
      email: "E-Mail",
      password: "Passwort",
      show: "Anzeigen",
      hide: "Ausblenden",
      studentAccount: "Studierendenkonto",
      minPassword: "Mindestens 8 Zeichen",
      emailConfirmation: "Bestätigung per E-Mail",
      alreadyAccount: "Du hast schon ein Konto?",
      forgotPassword: "Passwort vergessen?",
      backLogin: "Zurück zur Anmeldung",
      createAccount: "Konto erstellen",
      login: "Anmelden",
      signup: "Konto erstellen",
      sendLink: "Link senden",
      loading: "Bitte warten...",
    },
    placeholders: {
      firstName: "Dein Vorname",
      lastName: "Dein Nachname",
      email: "du@beispiel.de",
    },
    messages: {
      resetSent: "Wenn diese E-Mail registriert ist, haben wir einen Link gesendet.",
      checkEmail: "Prüfe deine E-Mails, um fortzufahren.",
      invalidLogin: "E-Mail oder Passwort ist falsch.",
      generic: "Das hat gerade nicht funktioniert. Bitte versuche es noch einmal.",
      signupError: "Das Konto konnte nicht erstellt werden. Prüfe deine Angaben und versuche es erneut.",
      resetError: "Der Link konnte nicht gesendet werden. Bitte versuche es erneut.",
    },
    mobile: {
      signupLink: "Konto erstellen",
      loginLink: "Anmelden",
    },
  },
  shell: {
    studentNameFallback: "Student",
    skip: "Zum Inhalt springen",
    studentFile: "Studienbereich",
    studyProject: "Studienplan für Deutschland",
    navigation: "Navigation",
    studentNavigation: "Studierenden-Navigation",
    studentMobileNavigation: "Mobile Studierenden-Navigation",
    groups: ["Mein Bereich", "Mein Weg", "Ressourcen"],
    items: [
      ["Übersicht", "Alles auf einen Blick"],
      ["Studienplan", "Hier starte ich"],
      ["Mein Weg", "Meine Schritte in Deutschland"],
      ["Profil", "Meine Angaben"],
      ["Unterlagen", "Dateien und Status"],
      ["Studiengänge", "Optionen vergleichen"],
      ["Sprachkurse", "Kurse zum Vergleichen"],
      ["Finanzierung & Versicherung", "Geprüfte Optionen"],
      ["Nächste Schritte", "Was als Nächstes ansteht"],
      ["Bewerbungen", "Stand und Fristen"],
    ],
    footer: "AlmaGo hilft dir bei der Vorbereitung. Offizielle Stellen treffen die Entscheidungen.",
    logout: "Abmelden",
    hello: "Hallo",
    mobileIntro: "Wähle, was du öffnen möchtest.",
    personalFile: "Mein Bereich",
    desktopIntro: "Hier siehst du, was als Nächstes deine Aufmerksamkeit braucht.",
    openMenu: "Studierendenmenü öffnen",
    closeMenu: "Studierendenmenü schließen",
    menu: "Menü",
    close: "Schließen",
  },
} as const;

export const nativeCopy = { fr, ar, en, de } as const;

export type NativeCopy = (typeof nativeCopy)[Locale];

export function getNativeCopy(locale: Locale): NativeCopy {
  return nativeCopy[locale];
}
