import type { Locale } from "@/lib/i18n";

/**
 * Signup copy for the orientation-linked, free Prospect journey.
 * Generic post-submit copy deliberately does not disclose account existence.
 */
export const orientationSignupCopy = {
  fr: {
    eyebrow: "Votre orientation est sauvegardée",
    title: "Créer mon espace Prospect gratuit",
    description: "Retrouvez votre orientation et préparez votre projet avec Campus Allemagne. Aucun paiement n’est demandé.",
    badge: "Espace Prospect gratuit",
    storyTitle: "Votre projet continue ici.",
    storyDescription: "Un espace gratuit pour retrouver votre orientation, compléter votre profil et découvrir les prochaines étapes.",
    storyPoints: [
      ["Votre orientation", "Retrouvez les résultats déjà reçus par e-mail."],
      ["Votre espace gratuit", "Gardez vos informations au même endroit."],
      ["La prochaine étape", "Campus Allemagne pourra examiner votre projet."],
    ],
    boundary: "L'espace étudiant et les documents ne sont pas activés automatiquement.",
    submit: "Créer mon espace Prospect gratuit",
    pendingTitle: "Vérifiez votre boîte e-mail",
    nextStepTitle: "Que faire maintenant ?",
    pendingDescription: "Votre demande a été prise en compte. Si une confirmation est nécessaire, vous recevrez un e-mail. Consultez aussi vos spams.",
    existingHint: "Vous avez déjà un compte ? Aucun nouvel e-mail de confirmation ne sera forcément envoyé. Connectez-vous avec votre ancien mot de passe, ou réinitialisez-le.",
    openInbox: "Ouvrir ma boîte Gmail",
    login: "J’ai déjà un compte : me connecter",
    recover: "Mot de passe oublié ?",
    resend: "Demander un nouvel e-mail de confirmation",
    resendLoading: "Demande en cours…",
    resendSuccess: "Votre demande a été traitée. Si l’adresse attend encore une confirmation, un e-mail pourra arriver. Vérifiez aussi vos spams.",
    resendFailure: "Impossible de demander un nouvel e-mail maintenant. Réessayez plus tard ou utilisez la connexion.",
    retry: "Revenir au formulaire",
    emailLabel: "Adresse concernée",
    genericTitle: "Vérifiez votre boîte e-mail",
    genericDescription: "Si une inscription doit être confirmée, vous recevrez un e-mail. Si vous avez déjà un compte, connectez-vous directement.",
    genericBadge: "Compte en cours de vérification",
  },
  ar: {
    eyebrow: "تم حفظ توجيهك",
    title: "إنشاء مساحة Prospect المجانية",
    description: "احتفظ بنتيجة توجيهك وتابع مشروعك مع Campus Allemagne مجانًا. لا يُطلب أي دفع الآن.",
    badge: "مساحة Prospect مجانية",
    storyTitle: "تابع مشروعك من هنا.",
    storyDescription: "مساحة مجانية للاطلاع على توجيهك واستكمال معلوماتك ومعرفة الخطوات التالية.",
    storyPoints: [
      ["نتيجة التوجيه", "اطّلع على النتائج التي وصلتك عبر البريد."],
      ["مساحتك المجانية", "احتفظ بمعلوماتك في مكان واحد."],
      ["الخطوة التالية", "يمكن لـ Campus Allemagne دراسة مشروعك."],
    ],
    boundary: "لا تُفتح مساحة الطالب أو الوثائق تلقائيًا.",
    submit: "إنشاء مساحة Prospect المجانية",
    pendingTitle: "تحقق من بريدك الإلكتروني",
    nextStepTitle: "ماذا تفعل الآن؟",
    pendingDescription: "تم استلام طلبك. إذا كانت هناك حاجة لتأكيد الحساب، فقد تصلك رسالة. تحقق أيضًا من البريد غير المرغوب فيه.",
    existingHint: "هل لديك حساب سابق؟ قد لا تصلك رسالة تأكيد جديدة. سجّل الدخول بكلمة المرور القديمة أو استعدها.",
    openInbox: "فتح Gmail",
    login: "لدي حساب بالفعل: تسجيل الدخول",
    recover: "نسيت كلمة المرور؟",
    resend: "طلب إعادة إرسال رسالة التأكيد",
    resendLoading: "جارٍ إرسال الطلب…",
    resendSuccess: "تمت معالجة الطلب. إذا كان الحساب يحتاج إلى تأكيد فقد تصلك رسالة. تحقق من البريد غير المرغوب فيه.",
    resendFailure: "تعذر إرسال طلب جديد الآن. حاول لاحقًا أو سجّل الدخول.",
    retry: "العودة إلى النموذج",
    emailLabel: "البريد المستخدم",
    genericTitle: "تحقق من بريدك الإلكتروني",
    genericDescription: "إذا كان الحساب يحتاج إلى تأكيد فستصلك رسالة. إذا كان لديك حساب سابق، سجّل الدخول مباشرة.",
    genericBadge: "جارٍ التحقق من الحساب",
  },
  en: {
    eyebrow: "Your orientation is saved",
    title: "Create my free Prospect space",
    description: "Keep your orientation and continue preparing your project with Campus Allemagne, free of charge.",
    badge: "Free Prospect space",
    storyTitle: "Your next step starts here.",
    storyDescription: "A free space to revisit your orientation, complete your profile and see what comes next.",
    storyPoints: [
      ["Your orientation", "Find the results already sent to your email."],
      ["Your free space", "Keep your information together."],
      ["Your next step", "Campus Allemagne can review your project."],
    ],
    boundary: "Student access and documents are not enabled automatically.",
    submit: "Create my free Prospect space",
    pendingTitle: "Check your email",
    nextStepTitle: "What can you do next?",
    pendingDescription: "Your request has been received. If confirmation is needed, an email will be sent. Please check spam too.",
    existingHint: "Already have an account? You may not receive another confirmation email. Sign in with your existing password or reset it.",
    openInbox: "Open Gmail",
    login: "I already have an account: sign in",
    recover: "Forgot your password?",
    resend: "Request another confirmation email",
    resendLoading: "Requesting…",
    resendSuccess: "Request processed. If the address still needs confirmation, an email may arrive. Check spam too.",
    resendFailure: "We couldn't request another email right now. Please try later or sign in.",
    retry: "Back to signup",
    emailLabel: "Email address",
    genericTitle: "Check your email",
    genericDescription: "If registration needs confirmation, you'll receive an email. If you already have an account, sign in instead.",
    genericBadge: "Account verification",
  },
  de: {
    eyebrow: "Deine Orientierung ist gespeichert",
    title: "Kostenlosen Prospect-Bereich erstellen",
    description: "Behalte deine Orientierung und plane deine nächsten Schritte mit Campus Allemagne – kostenlos.",
    badge: "Kostenloser Prospect-Bereich",
    storyTitle: "Hier geht dein Projekt weiter.",
    storyDescription: "Ein kostenloser Bereich für deine Orientierung, deine Angaben und die nächsten Schritte.",
    storyPoints: [
      ["Deine Orientierung", "Finde deine bereits per E-Mail erhaltenen Ergebnisse."],
      ["Dein kostenloser Bereich", "Alle Informationen an einem Ort."],
      ["Dein nächster Schritt", "Campus Allemagne kann dein Projekt prüfen."],
    ],
    boundary: "Studierendenbereich und Dokumente werden nicht automatisch freigeschaltet.",
    submit: "Kostenlosen Prospect-Bereich erstellen",
    pendingTitle: "Prüfe dein E-Mail-Postfach",
    nextStepTitle: "Was kannst du jetzt tun?",
    pendingDescription: "Deine Anfrage ist eingegangen. Falls eine Bestätigung nötig ist, bekommst du eine E-Mail. Prüfe auch den Spam-Ordner.",
    existingHint: "Du hast schon ein Konto? Dann wird möglicherweise keine weitere Bestätigung verschickt. Melde dich an oder setze dein Passwort zurück.",
    openInbox: "Gmail öffnen",
    login: "Ich habe ein Konto: anmelden",
    recover: "Passwort vergessen?",
    resend: "Weitere Bestätigungs-E-Mail anfordern",
    resendLoading: "Anfrage läuft…",
    resendSuccess: "Anfrage bearbeitet. Falls die Adresse noch bestätigt werden muss, kann eine E-Mail ankommen. Prüfe auch Spam.",
    resendFailure: "Derzeit kann keine weitere E-Mail angefordert werden. Versuche es später oder melde dich an.",
    retry: "Zurück zur Registrierung",
    emailLabel: "Verwendete E-Mail-Adresse",
    genericTitle: "Prüfe dein E-Mail-Postfach",
    genericDescription: "Falls eine Bestätigung nötig ist, bekommst du eine E-Mail. Wenn du schon ein Konto hast, melde dich an.",
    genericBadge: "Kontobestätigung",
  },
} as const satisfies Record<Locale, Record<string, string | readonly (readonly [string, string])[]>>;
