import type { Locale } from "@/lib/i18n";

export const provisionalCopy = {
  fr: {
    eyebrow: "DÉCOUVERTE GRATUITE",
    title: "Bienvenue dans votre espace Prospect provisoire",
    intro: "Explorez les programmes et les prochaines étapes sans attendre. Cet accès provisoire n'est pas encore un compte confirmé.",
    alert: "Confirmez votre e-mail pour accéder aux fonctionnalités personnelles et enregistrer durablement vos démarches.",
    verify: "Vérifier mon e-mail",
    resend: "Je n'ai pas reçu d'e-mail",
    login: "Déjà un compte ? Se connecter",
    orientation: "Mon orientation",
    orientationEmpty: "Vous pouvez commencer une orientation gratuite pour personnaliser ces recommandations.",
    orientationAction: "Faire mon orientation",
    degree: "Niveau envisagé",
    field: "Domaine souhaité",
    language: "Niveau d'allemand déclaré",
    programmes: "Explorer les programmes vérifiés",
    catalogueEmpty: "Le catalogue public est momentanément indisponible. Réessayez plus tard.",
    search: "Rechercher un programme ou une ville",
    noMatch: "Aucun programme ne correspond à cette recherche.",
    official: "Voir la source officielle",
    steps: "Les étapes de mon projet",
    step1: "Revoir mon orientation",
    step2: "Comparer les programmes et les exigences",
    step3: "Préparer la langue, le budget et les dates",
    step4: "Vérifier mon e-mail pour enregistrer mon projet",
    solutions: "À découvrir aussi",
    solutionsText: "Langues, financement, assurance et offres : consultez les informations publiques. Les demandes, messages, documents et paiements restent verrouillés.",
    sensitive: "Fonctions réservées aux comptes vérifiés",
    restricted: "Envoi de documents, messages personnels, demandes de suivi, modification du dossier et paiement.",
    notice: "Cet espace est une consultation provisoire : ni dossier définitif, ni admission, ni paiement. Aucun compte n'est considéré comme vérifié ici.",
    quit: "Quitter cet accès provisoire",
  },
  ar: {
    eyebrow: "استكشاف مجاني",
    title: "مرحبًا في مساحة Prospect المؤقتة",
    intro: "استكشف البرامج والخطوات القادمة دون انتظار. هذا الوصول المؤقت ليس حسابًا مؤكدًا.",
    alert: "أكد بريدك الإلكتروني للاستفادة من الوظائف الشخصية وحفظ خطواتك بشكل دائم.",
    verify: "تأكيد بريدي الإلكتروني",
    resend: "لم أتلق رسالة",
    login: "لديك حساب؟ تسجيل الدخول",
    orientation: "توجيهي",
    orientationEmpty: "يمكنك بدء توجيه مجاني للحصول على نتائج تناسب مشروعك.",
    orientationAction: "ابدأ التوجيه",
    degree: "المستوى المطلوب",
    field: "التخصص المطلوب",
    language: "مستوى الألمانية المصرح به",
    programmes: "تصفح البرامج المتحقق منها",
    catalogueEmpty: "الكتالوج العام غير متاح مؤقتًا. حاول لاحقًا.",
    search: "ابحث عن برنامج أو مدينة",
    noMatch: "لا توجد برامج تطابق بحثك.",
    official: "المصدر الرسمي",
    steps: "خطوات مشروعي",
    step1: "مراجعة التوجيه",
    step2: "مقارنة البرامج والشروط",
    step3: "الاستعداد للغة والميزانية والمواعيد",
    step4: "تأكيد البريد لحفظ المشروع",
    solutions: "يمكنك اكتشاف المزيد",
    solutionsText: "اللغة والتمويل والتأمين والعروض: تصفح المعلومات العامة. تبقى الوثائق والرسائل والطلبات والدفع مقفلة.",
    sensitive: "وظائف للحسابات المؤكدة فقط",
    restricted: "رفع الوثائق، الرسائل الخاصة، طلب المتابعة، تعديل الملف والدفع.",
    notice: "هذا وصول مؤقت للعرض وليس ملفًا نهائيًا أو قبولًا أو دفعًا. لم يُتحقق من أي حساب عبر هذه الصفحة.",
    quit: "الخروج من المساحة المؤقتة",
  },
  en: {
    eyebrow: "FREE EXPLORATION",
    title: "Welcome to your provisional Prospect space",
    intro: "Explore programmes and next steps right away. This temporary access is not a confirmed account.",
    alert: "Verify your email to access personal features and save your progress permanently.",
    verify: "Verify my email",
    resend: "I didn't receive an email",
    login: "Already have an account? Sign in",
    orientation: "My orientation",
    orientationEmpty: "Start a free orientation for personalised suggestions.",
    orientationAction: "Start my orientation",
    degree: "Target degree",
    field: "Preferred field",
    language: "Declared German level",
    programmes: "Explore verified programmes",
    catalogueEmpty: "The public catalogue is currently unavailable. Please try again later.",
    search: "Search programmes or cities",
    noMatch: "No programmes match your search.",
    official: "Official source",
    steps: "My project steps",
    step1: "Review my orientation",
    step2: "Compare programmes and requirements",
    step3: "Plan language, budget and deadlines",
    step4: "Verify my email to save my project",
    solutions: "Discover more",
    solutionsText: "Languages, funding, insurance and offers: explore public information. Requests, messages, documents and payments remain locked.",
    sensitive: "Verified-account features only",
    restricted: "Document uploads, private messages, follow-up requests, dossier edits and payments.",
    notice: "This is a temporary read-only preview, not an activated file, admission or payment. No account is treated as verified here.",
    quit: "Leave provisional access",
  },
  de: {
    eyebrow: "KOSTENLOS ENTDECKEN",
    title: "Willkommen im vorläufigen Prospect-Bereich",
    intro: "Entdecke Programme und nächste Schritte direkt. Dieser vorläufige Zugang ist noch kein bestätigtes Konto.",
    alert: "Bestätige deine E-Mail, um persönliche Funktionen zu nutzen und Fortschritte dauerhaft zu speichern.",
    verify: "E-Mail bestätigen",
    resend: "Keine E-Mail erhalten",
    login: "Bereits ein Konto? Anmelden",
    orientation: "Meine Orientierung",
    orientationEmpty: "Starte eine kostenlose Orientierung für persönliche Empfehlungen.",
    orientationAction: "Orientierung starten",
    degree: "Angestrebter Abschluss",
    field: "Gewünschtes Fach",
    language: "Angegebenes Deutschniveau",
    programmes: "Geprüfte Programme entdecken",
    catalogueEmpty: "Der öffentliche Katalog ist derzeit nicht verfügbar. Versuche es später erneut.",
    search: "Nach Programm oder Stadt suchen",
    noMatch: "Keine passenden Programme gefunden.",
    official: "Offizielle Quelle",
    steps: "Meine nächsten Schritte",
    step1: "Orientierung ansehen",
    step2: "Programme und Anforderungen vergleichen",
    step3: "Sprache, Budget und Termine vorbereiten",
    step4: "E-Mail bestätigen, um das Projekt zu speichern",
    solutions: "Mehr entdecken",
    solutionsText: "Sprachen, Finanzierung, Versicherung und Angebote: Öffentliche Informationen ansehen. Anfragen, Nachrichten, Dokumente und Zahlungen bleiben gesperrt.",
    sensitive: "Nur für bestätigte Konten",
    restricted: "Dokument-Uploads, private Nachrichten, Beratung, Dossieränderungen und Zahlungen.",
    notice: "Dies ist eine vorläufige Leseansicht, kein aktiviertes Dossier, keine Zulassung oder Zahlung. Hier gilt kein Konto als bestätigt.",
    quit: "Vorläufigen Zugang verlassen",
  },
} as const satisfies Record<Locale, Record<string, string>>;
